export const demoTransactions = [
  // ========================================
  // MAY 2026 - Start of FY 2026-2027
  // ========================================
  {
    id: 'demo-1',
    date: new Date('2026-05-03'),
    category: 'Concessions (D)',
    voucherNumber: 1,
    vendor: 'Baseball Game Sales',
    amount: 380.0,
    type: 'DEPOSIT',
    cleared: true,
    notes: null,
    receipts: [],
    createdAt: new Date('2026-05-03'),
    updatedAt: new Date('2026-05-03'),
    voucher: {
      id: 'v-1',
      voucherNumber: 1,
      receiptImageUrl: null,
      notes: 'Baseball home game concessions',
      createdAt: new Date('2026-05-03'),
      updatedAt: new Date('2026-05-03'),
    },
  },
  {
    id: 'demo-2',
    date: new Date('2026-05-08'),
    category: 'Donations (D)',
    voucherNumber: 2,
    vendor: 'Alumni Association',
    amount: 1500.0,
    type: 'DEPOSIT',
    cleared: true,
    notes: null,
    receipts: [],
    createdAt: new Date('2026-05-08'),
    updatedAt: new Date('2026-05-08'),
    voucher: {
      id: 'v-2',
      voucherNumber: 2,
      receiptImageUrl: null,
      notes: 'Annual alumni donation',
      createdAt: new Date('2026-05-08'),
      updatedAt: new Date('2026-05-08'),
    },
  },
  {
    id: 'demo-3',
    date: new Date('2026-05-12'),
    category: 'Fundraiser (D)',
    voucherNumber: 3,
    vendor: 'Concession Stand Rental',
    amount: 200.0,
    type: 'DEPOSIT',
    cleared: true,
    notes: null,
    receipts: [],
    createdAt: new Date('2026-05-12'),
    updatedAt: new Date('2026-05-12'),
    voucher: {
      id: 'v-3',
      voucherNumber: 3,
      receiptImageUrl: null,
      notes: 'Rented concession stand for event',
      createdAt: new Date('2026-05-12'),
      updatedAt: new Date('2026-05-12'),
    },
  },
  {
    id: 'demo-4',
    date: new Date('2026-05-15'),
    category: 'Interest Checking (D)',
    voucherNumber: 4,
    vendor: 'First National Bank',
    amount: 16.85,
    type: 'DEPOSIT',
    cleared: true,
    notes: null,
    receipts: [],
    createdAt: new Date('2026-05-15'),
    updatedAt: new Date('2026-05-15'),
    voucher: {
      id: 'v-4',
      voucherNumber: 4,
      receiptImageUrl: null,
      notes: 'Monthly interest credit',
      createdAt: new Date('2026-05-15'),
      updatedAt: new Date('2026-05-15'),
    },
  },
  {
    id: 'demo-5',
    date: new Date('2026-05-18'),
    category: 'Other (D)',
    voucherNumber: 5,
    vendor: 'Spring Concert Tickets',
    amount: 420.0,
    type: 'DEPOSIT',
    cleared: true,
    notes: null,
    receipts: [],
    createdAt: new Date('2026-05-18'),
    updatedAt: new Date('2026-05-18'),
    voucher: {
      id: 'v-5',
      voucherNumber: 5,
      receiptImageUrl: null,
      notes: 'Spring concert ticket sales',
      createdAt: new Date('2026-05-18'),
      updatedAt: new Date('2026-05-18'),
    },
  },
  {
    id: 'demo-6',
    date: new Date('2026-05-22'),
    category: 'Credit Card Machine (D)',
    voucherNumber: 6,
    vendor: 'Square Processing',
    amount: 310.0,
    type: 'DEPOSIT',
    cleared: true,
    notes: null,
    receipts: [],
    createdAt: new Date('2026-05-22'),
    updatedAt: new Date('2026-05-22'),
    voucher: {
      id: 'v-6',
      voucherNumber: 6,
      receiptImageUrl: null,
      notes: 'Credit card batch — May events',
      createdAt: new Date('2026-05-22'),
      updatedAt: new Date('2026-05-22'),
    },
  },
  {
    id: 'demo-7',
    date: new Date('2026-05-05'),
    category: 'Concessions (W)',
    voucherNumber: 7,
    vendor: 'Sysco Food Services',
    amount: 315.0,
    type: 'WITHDRAWAL',
    cleared: true,
    notes: null,
    receipts: [],
    createdAt: new Date('2026-05-05'),
    updatedAt: new Date('2026-05-05'),
    voucher: {
      id: 'v-7',
      voucherNumber: 7,
      receiptImageUrl: null,
      notes: 'End of year event supplies',
      createdAt: new Date('2026-05-05'),
      updatedAt: new Date('2026-05-05'),
    },
  },
  {
    id: 'demo-8',
    date: new Date('2026-05-20'),
    category: 'Interest Checking (W)',
    voucherNumber: 8,
    vendor: 'First National Bank',
    amount: 5.0,
    type: 'WITHDRAWAL',
    cleared: true,
    notes: null,
    receipts: [],
    createdAt: new Date('2026-05-20'),
    updatedAt: new Date('2026-05-20'),
    voucher: {
      id: 'v-8',
      voucherNumber: 8,
      receiptImageUrl: null,
      notes: 'Monthly account service fee',
      createdAt: new Date('2026-05-20'),
      updatedAt: new Date('2026-05-20'),
    },
  },
  {
    id: 'demo-9',
    date: new Date('2026-05-25'),
    category: 'Other (W)',
    voucherNumber: 9,
    vendor: 'VFW Hall',
    amount: 300.0,
    type: 'WITHDRAWAL',
    cleared: true,
    notes: null,
    receipts: [],
    createdAt: new Date('2026-05-25'),
    updatedAt: new Date('2026-05-25'),
    voucher: {
      id: 'v-9',
      voucherNumber: 9,
      receiptImageUrl: null,
      notes: 'End of year banquet rental',
      createdAt: new Date('2026-05-25'),
      updatedAt: new Date('2026-05-25'),
    },
  },
  {
    id: 'demo-10',
    date: new Date('2026-05-28'),
    category: 'Director of Band (W)',
    voucherNumber: 10,
    vendor: 'Bands of America',
    amount: 450.0,
    type: 'WITHDRAWAL',
    cleared: true,
    notes: null,
    receipts: [],
    createdAt: new Date('2026-05-28'),
    updatedAt: new Date('2026-05-28'),
    voucher: {
      id: 'v-10',
      voucherNumber: 10,
      receiptImageUrl: null,
      notes: 'Competition registration fee',
      createdAt: new Date('2026-05-28'),
      updatedAt: new Date('2026-05-28'),
    },
  },

  // ========================================
  // JUNE 2026
  // ========================================
  {
    id: 'demo-11',
    date: new Date('2026-06-05'),
    category: 'Concessions (D)',
    voucherNumber: 11,
    vendor: 'Summer Camp Sales',
    amount: 780.0,
    type: 'DEPOSIT',
    cleared: true,
    notes: null,
    receipts: [],
    createdAt: new Date('2026-06-05'),
    updatedAt: new Date('2026-06-05'),
    voucher: {
      id: 'v-11',
      voucherNumber: 11,
      receiptImageUrl: null,
      notes: 'Band summer camp concessions',
      createdAt: new Date('2026-06-05'),
      updatedAt: new Date('2026-06-05'),
    },
  },
  {
    id: 'demo-12',
    date: new Date('2026-06-10'),
    category: 'Donations (D)',
    voucherNumber: 12,
    vendor: 'Parent Association',
    amount: 800.0,
    type: 'DEPOSIT',
    cleared: true,
    notes: null,
    receipts: [],
    createdAt: new Date('2026-06-10'),
    updatedAt: new Date('2026-06-10'),
    voucher: {
      id: 'v-12',
      voucherNumber: 12,
      receiptImageUrl: null,
      notes: 'Summer program funding',
      createdAt: new Date('2026-06-10'),
      updatedAt: new Date('2026-06-10'),
    },
  },
  {
    id: 'demo-13',
    date: new Date('2026-06-15'),
    category: 'Fundraiser (D)',
    voucherNumber: 13,
    vendor: 'Car Wash',
    amount: 320.0,
    type: 'DEPOSIT',
    cleared: true,
    notes: null,
    receipts: [],
    createdAt: new Date('2026-06-15'),
    updatedAt: new Date('2026-06-15'),
    voucher: {
      id: 'v-13',
      voucherNumber: 13,
      receiptImageUrl: null,
      notes: 'Summer car wash',
      createdAt: new Date('2026-06-15'),
      updatedAt: new Date('2026-06-15'),
    },
  },
  {
    id: 'demo-14',
    date: new Date('2026-06-15'),
    category: 'Interest Checking (D)',
    voucherNumber: 14,
    vendor: 'First National Bank',
    amount: 14.55,
    type: 'DEPOSIT',
    cleared: true,
    notes: null,
    receipts: [],
    createdAt: new Date('2026-06-15'),
    updatedAt: new Date('2026-06-15'),
    voucher: {
      id: 'v-14',
      voucherNumber: 14,
      receiptImageUrl: null,
      notes: 'Monthly interest credit',
      createdAt: new Date('2026-06-15'),
      updatedAt: new Date('2026-06-15'),
    },
  },
  {
    id: 'demo-15',
    date: new Date('2026-06-18'),
    category: 'Other (D)',
    voucherNumber: 15,
    vendor: 'Summer Camp Registration',
    amount: 450.0,
    type: 'DEPOSIT',
    cleared: true,
    notes: null,
    receipts: [],
    createdAt: new Date('2026-06-18'),
    updatedAt: new Date('2026-06-18'),
    voucher: {
      id: 'v-15',
      voucherNumber: 15,
      receiptImageUrl: null,
      notes: 'Band summer camp fees',
      createdAt: new Date('2026-06-18'),
      updatedAt: new Date('2026-06-18'),
    },
  },
  {
    id: 'demo-16',
    date: new Date('2026-06-22'),
    category: 'Credit Card Machine (D)',
    voucherNumber: 16,
    vendor: 'Square Processing',
    amount: 285.0,
    type: 'DEPOSIT',
    cleared: true,
    notes: null,
    receipts: [],
    createdAt: new Date('2026-06-22'),
    updatedAt: new Date('2026-06-22'),
    voucher: {
      id: 'v-16',
      voucherNumber: 16,
      receiptImageUrl: null,
      notes: 'Credit card batch — June events',
      createdAt: new Date('2026-06-22'),
      updatedAt: new Date('2026-06-22'),
    },
  },
  {
    id: 'demo-17',
    date: new Date('2026-06-08'),
    category: 'Concessions (W)',
    voucherNumber: 17,
    vendor: "Sam's Club",
    amount: 275.0,
    type: 'WITHDRAWAL',
    cleared: true,
    notes: null,
    receipts: [],
    createdAt: new Date('2026-06-08'),
    updatedAt: new Date('2026-06-08'),
    voucher: {
      id: 'v-17',
      voucherNumber: 17,
      receiptImageUrl: null,
      notes: 'Summer camp concession supplies',
      createdAt: new Date('2026-06-08'),
      updatedAt: new Date('2026-06-08'),
    },
  },
  {
    id: 'demo-18',
    date: new Date('2026-06-20'),
    category: 'Interest Checking (W)',
    voucherNumber: 18,
    vendor: 'First National Bank',
    amount: 5.0,
    type: 'WITHDRAWAL',
    cleared: true,
    notes: null,
    receipts: [],
    createdAt: new Date('2026-06-20'),
    updatedAt: new Date('2026-06-20'),
    voucher: {
      id: 'v-18',
      voucherNumber: 18,
      receiptImageUrl: null,
      notes: 'Monthly account service fee',
      createdAt: new Date('2026-06-20'),
      updatedAt: new Date('2026-06-20'),
    },
  },
  {
    id: 'demo-19',
    date: new Date('2026-06-25'),
    category: 'Other (W)',
    voucherNumber: 19,
    vendor: 'Staples',
    amount: 189.99,
    type: 'WITHDRAWAL',
    cleared: true,
    notes: null,
    receipts: [],
    createdAt: new Date('2026-06-25'),
    updatedAt: new Date('2026-06-25'),
    voucher: {
      id: 'v-19',
      voucherNumber: 19,
      receiptImageUrl: null,
      notes: 'Summer program supplies',
      createdAt: new Date('2026-06-25'),
      updatedAt: new Date('2026-06-25'),
    },
  },
  {
    id: 'demo-20',
    date: new Date('2026-06-28'),
    category: 'Director of Band (W)',
    voucherNumber: 20,
    vendor: 'Yamaha Music',
    amount: 3200.0,
    type: 'WITHDRAWAL',
    cleared: false,
    notes: null,
    receipts: [],
    createdAt: new Date('2026-06-28'),
    updatedAt: new Date('2026-06-28'),
    voucher: {
      id: 'v-20',
      voucherNumber: 20,
      receiptImageUrl: null,
      notes: 'New percussion equipment for fall',
      createdAt: new Date('2026-06-28'),
      updatedAt: new Date('2026-06-28'),
    },
  },

  // ========================================
  // JULY 2026
  // ========================================
  {
    id: 'demo-21',
    date: new Date('2026-07-04'),
    category: 'Concessions (D)',
    voucherNumber: 21,
    vendor: 'July 4th Festival',
    amount: 950.0,
    type: 'DEPOSIT',
    cleared: true,
    notes: null,
    receipts: [],
    createdAt: new Date('2026-07-04'),
    updatedAt: new Date('2026-07-04'),
    voucher: {
      id: 'v-21',
      voucherNumber: 21,
      receiptImageUrl: null,
      notes: 'Fourth of July parade concessions',
      createdAt: new Date('2026-07-04'),
      updatedAt: new Date('2026-07-04'),
    },
  },
  {
    id: 'demo-22',
    date: new Date('2026-07-08'),
    category: 'Donations (D)',
    voucherNumber: 22,
    vendor: 'Local Business Sponsorship',
    amount: 1200.0,
    type: 'DEPOSIT',
    cleared: true,
    notes: null,
    receipts: [],
    createdAt: new Date('2026-07-08'),
    updatedAt: new Date('2026-07-08'),
    voucher: {
      id: 'v-22',
      voucherNumber: 22,
      receiptImageUrl: null,
      notes: 'Summer sponsorship',
      createdAt: new Date('2026-07-08'),
      updatedAt: new Date('2026-07-08'),
    },
  },
  {
    id: 'demo-23',
    date: new Date('2026-07-12'),
    category: 'Fundraiser (D)',
    voucherNumber: 23,
    vendor: 'Ice Cream Social',
    amount: 280.0,
    type: 'DEPOSIT',
    cleared: true,
    notes: null,
    receipts: [],
    createdAt: new Date('2026-07-12'),
    updatedAt: new Date('2026-07-12'),
    voucher: {
      id: 'v-23',
      voucherNumber: 23,
      receiptImageUrl: null,
      notes: 'Summer ice cream social fundraiser',
      createdAt: new Date('2026-07-12'),
      updatedAt: new Date('2026-07-12'),
    },
  },
  {
    id: 'demo-24',
    date: new Date('2026-07-15'),
    category: 'Interest Checking (D)',
    voucherNumber: 24,
    vendor: 'First National Bank',
    amount: 13.22,
    type: 'DEPOSIT',
    cleared: true,
    notes: null,
    receipts: [],
    createdAt: new Date('2026-07-15'),
    updatedAt: new Date('2026-07-15'),
    voucher: {
      id: 'v-24',
      voucherNumber: 24,
      receiptImageUrl: null,
      notes: 'Monthly interest credit',
      createdAt: new Date('2026-07-15'),
      updatedAt: new Date('2026-07-15'),
    },
  },
  {
    id: 'demo-25',
    date: new Date('2026-07-18'),
    category: 'Other (D)',
    voucherNumber: 25,
    vendor: 'Pool Party Rental',
    amount: 350.0,
    type: 'DEPOSIT',
    cleared: true,
    notes: null,
    receipts: [],
    createdAt: new Date('2026-07-18'),
    updatedAt: new Date('2026-07-18'),
    voucher: {
      id: 'v-25',
      voucherNumber: 25,
      receiptImageUrl: null,
      notes: 'Community pool party rental income',
      createdAt: new Date('2026-07-18'),
      updatedAt: new Date('2026-07-18'),
    },
  },
  {
    id: 'demo-26',
    date: new Date('2026-07-22'),
    category: 'Credit Card Machine (D)',
    voucherNumber: 26,
    vendor: 'Square Processing',
    amount: 240.0,
    type: 'DEPOSIT',
    cleared: true,
    notes: null,
    receipts: [],
    createdAt: new Date('2026-07-22'),
    updatedAt: new Date('2026-07-22'),
    voucher: {
      id: 'v-26',
      voucherNumber: 26,
      receiptImageUrl: null,
      notes: 'Credit card batch — July events',
      createdAt: new Date('2026-07-22'),
      updatedAt: new Date('2026-07-22'),
    },
  },
  {
    id: 'demo-27',
    date: new Date('2026-07-05'),
    category: 'Concessions (W)',
    voucherNumber: 27,
    vendor: 'Coca-Cola Distributing',
    amount: 245.0,
    type: 'WITHDRAWAL',
    cleared: true,
    notes: null,
    receipts: [],
    createdAt: new Date('2026-07-05'),
    updatedAt: new Date('2026-07-05'),
    voucher: {
      id: 'v-27',
      voucherNumber: 27,
      receiptImageUrl: null,
      notes: 'Festival beverage order',
      createdAt: new Date('2026-07-05'),
      updatedAt: new Date('2026-07-05'),
    },
  },
  {
    id: 'demo-28',
    date: new Date('2026-07-20'),
    category: 'Interest Checking (W)',
    voucherNumber: 28,
    vendor: 'First National Bank',
    amount: 5.0,
    type: 'WITHDRAWAL',
    cleared: true,
    notes: null,
    receipts: [],
    createdAt: new Date('2026-07-20'),
    updatedAt: new Date('2026-07-20'),
    voucher: {
      id: 'v-28',
      voucherNumber: 28,
      receiptImageUrl: null,
      notes: 'Monthly account service fee',
      createdAt: new Date('2026-07-20'),
      updatedAt: new Date('2026-07-20'),
    },
  },
  {
    id: 'demo-29',
    date: new Date('2026-07-25'),
    category: 'Other (W)',
    voucherNumber: 29,
    vendor: 'Office Depot',
    amount: 156.5,
    type: 'WITHDRAWAL',
    cleared: true,
    notes: null,
    receipts: [],
    createdAt: new Date('2026-07-25'),
    updatedAt: new Date('2026-07-25'),
    voucher: {
      id: 'v-29',
      voucherNumber: 29,
      receiptImageUrl: null,
      notes: 'Program printing',
      createdAt: new Date('2026-07-25'),
      updatedAt: new Date('2026-07-25'),
    },
  },
  {
    id: 'demo-30',
    date: new Date('2026-07-28'),
    category: 'Director of Band (W)',
    voucherNumber: 30,
    vendor: 'Hal Leonard Music',
    amount: 890.0,
    type: 'WITHDRAWAL',
    cleared: true,
    notes: null,
    receipts: [],
    createdAt: new Date('2026-07-28'),
    updatedAt: new Date('2026-07-28'),
    voucher: {
      id: 'v-30',
      voucherNumber: 30,
      receiptImageUrl: null,
      notes: 'Fall show music order',
      createdAt: new Date('2026-07-28'),
      updatedAt: new Date('2026-07-28'),
    },
  },

  // ========================================
  // AUGUST 2026
  // ========================================
  {
    id: 'demo-31',
    date: new Date('2026-08-05'),
    category: 'Concessions (D)',
    voucherNumber: 31,
    vendor: 'Football Scrimmage Sales',
    amount: 420.0,
    type: 'DEPOSIT',
    cleared: true,
    notes: null,
    receipts: [],
    createdAt: new Date('2026-08-05'),
    updatedAt: new Date('2026-08-05'),
    voucher: {
      id: 'v-31',
      voucherNumber: 31,
      receiptImageUrl: null,
      notes: 'Fall football scrimmage concessions',
      createdAt: new Date('2026-08-05'),
      updatedAt: new Date('2026-08-05'),
    },
  },
  {
    id: 'demo-32',
    date: new Date('2026-08-10'),
    category: 'Donations (D)',
    voucherNumber: 32,
    vendor: 'Miller Family Trust',
    amount: 1200.0,
    type: 'DEPOSIT',
    cleared: true,
    notes: null,
    receipts: [],
    createdAt: new Date('2026-08-10'),
    updatedAt: new Date('2026-08-10'),
    voucher: {
      id: 'v-32',
      voucherNumber: 32,
      receiptImageUrl: null,
      notes: 'Annual trust donation',
      createdAt: new Date('2026-08-10'),
      updatedAt: new Date('2026-08-10'),
    },
  },
  {
    id: 'demo-33',
    date: new Date('2026-08-15'),
    category: 'Fundraiser (D)',
    voucherNumber: 33,
    vendor: 'Back-to-School BBQ',
    amount: 680.0,
    type: 'DEPOSIT',
    cleared: true,
    notes: null,
    receipts: [],
    createdAt: new Date('2026-08-15'),
    updatedAt: new Date('2026-08-15'),
    voucher: {
      id: 'v-33',
      voucherNumber: 33,
      receiptImageUrl: null,
      notes: 'Annual back-to-school BBQ',
      createdAt: new Date('2026-08-15'),
      updatedAt: new Date('2026-08-15'),
    },
  },
  {
    id: 'demo-34',
    date: new Date('2026-08-15'),
    category: 'Interest Checking (D)',
    voucherNumber: 34,
    vendor: 'First National Bank',
    amount: 12.88,
    type: 'DEPOSIT',
    cleared: true,
    notes: null,
    receipts: [],
    createdAt: new Date('2026-08-15'),
    updatedAt: new Date('2026-08-15'),
    voucher: {
      id: 'v-34',
      voucherNumber: 34,
      receiptImageUrl: null,
      notes: 'Monthly interest credit',
      createdAt: new Date('2026-08-15'),
      updatedAt: new Date('2026-08-15'),
    },
  },
  {
    id: 'demo-35',
    date: new Date('2026-08-18'),
    category: 'Other (D)',
    voucherNumber: 35,
    vendor: 'Band Camp Registration',
    amount: 600.0,
    type: 'DEPOSIT',
    cleared: true,
    notes: null,
    receipts: [],
    createdAt: new Date('2026-08-18'),
    updatedAt: new Date('2026-08-18'),
    voucher: {
      id: 'v-35',
      voucherNumber: 35,
      receiptImageUrl: null,
      notes: 'Band camp registration fees',
      createdAt: new Date('2026-08-18'),
      updatedAt: new Date('2026-08-18'),
    },
  },
  {
    id: 'demo-36',
    date: new Date('2026-08-22'),
    category: 'Credit Card Machine (D)',
    voucherNumber: 36,
    vendor: 'Square Processing',
    amount: 380.0,
    type: 'DEPOSIT',
    cleared: true,
    notes: null,
    receipts: [],
    createdAt: new Date('2026-08-22'),
    updatedAt: new Date('2026-08-22'),
    voucher: {
      id: 'v-36',
      voucherNumber: 36,
      receiptImageUrl: null,
      notes: 'Credit card batch — August events',
      createdAt: new Date('2026-08-22'),
      updatedAt: new Date('2026-08-22'),
    },
  },
  {
    id: 'demo-37',
    date: new Date('2026-08-05'),
    category: 'Concessions (W)',
    voucherNumber: 37,
    vendor: 'Sysco Food Services',
    amount: 385.0,
    type: 'WITHDRAWAL',
    cleared: true,
    notes: null,
    receipts: [],
    createdAt: new Date('2026-08-05'),
    updatedAt: new Date('2026-08-05'),
    voucher: {
      id: 'v-37',
      voucherNumber: 37,
      receiptImageUrl: null,
      notes: 'Football season concession stock',
      createdAt: new Date('2026-08-05'),
      updatedAt: new Date('2026-08-05'),
    },
  },
  {
    id: 'demo-38',
    date: new Date('2026-08-20'),
    category: 'Interest Checking (W)',
    voucherNumber: 38,
    vendor: 'First National Bank',
    amount: 5.0,
    type: 'WITHDRAWAL',
    cleared: true,
    notes: null,
    receipts: [],
    createdAt: new Date('2026-08-20'),
    updatedAt: new Date('2026-08-20'),
    voucher: {
      id: 'v-38',
      voucherNumber: 38,
      receiptImageUrl: null,
      notes: 'Monthly account service fee',
      createdAt: new Date('2026-08-20'),
      updatedAt: new Date('2026-08-20'),
    },
  },
  {
    id: 'demo-39',
    date: new Date('2026-08-25'),
    category: 'Other (W)',
    voucherNumber: 39,
    vendor: 'Amazon',
    amount: 299.99,
    type: 'WITHDRAWAL',
    cleared: true,
    notes: null,
    receipts: [],
    createdAt: new Date('2026-08-25'),
    updatedAt: new Date('2026-08-25'),
    voucher: {
      id: 'v-39',
      voucherNumber: 39,
      receiptImageUrl: null,
      notes: 'Drill and equipment supplies',
      createdAt: new Date('2026-08-25'),
      updatedAt: new Date('2026-08-25'),
    },
  },
  {
    id: 'demo-40',
    date: new Date('2026-08-28'),
    category: 'Director of Band (W)',
    voucherNumber: 40,
    vendor: 'Music Theatre Intl',
    amount: 750.0,
    type: 'WITHDRAWAL',
    cleared: true,
    notes: null,
    receipts: [],
    createdAt: new Date('2026-08-28'),
    updatedAt: new Date('2026-08-28'),
    voucher: {
      id: 'v-40',
      voucherNumber: 40,
      receiptImageUrl: null,
      notes: 'Show licensing fees',
      createdAt: new Date('2026-08-28'),
      updatedAt: new Date('2026-08-28'),
    },
  },

  // ========================================
  // SEPTEMBER 2026
  // ========================================
  {
    id: 'demo-41',
    date: new Date('2026-09-05'),
    category: 'Concessions (D)',
    voucherNumber: 41,
    vendor: 'Friday Night Football Sales',
    amount: 875.5,
    type: 'DEPOSIT',
    cleared: true,
    notes: null,
    receipts: [],
    createdAt: new Date('2026-09-05'),
    updatedAt: new Date('2026-09-05'),
    voucher: {
      id: 'v-41',
      voucherNumber: 41,
      receiptImageUrl: null,
      notes: 'First home game concessions',
      createdAt: new Date('2026-09-05'),
      updatedAt: new Date('2026-09-05'),
    },
  },
  {
    id: 'demo-42',
    date: new Date('2026-09-08'),
    category: 'Donations (D)',
    voucherNumber: 42,
    vendor: 'Johnson Family',
    amount: 550.0,
    type: 'DEPOSIT',
    cleared: true,
    notes: null,
    receipts: [],
    createdAt: new Date('2026-09-08'),
    updatedAt: new Date('2026-09-08'),
    voucher: {
      id: 'v-42',
      voucherNumber: 42,
      receiptImageUrl: null,
      notes: 'Fall donation',
      createdAt: new Date('2026-09-08'),
      updatedAt: new Date('2026-09-08'),
    },
  },
  {
    id: 'demo-43',
    date: new Date('2026-09-12'),
    category: 'Fundraiser (D)',
    voucherNumber: 43,
    vendor: 'Cookie Dough Sales',
    amount: 1350.0,
    type: 'DEPOSIT',
    cleared: true,
    notes: null,
    receipts: [],
    createdAt: new Date('2026-09-12'),
    updatedAt: new Date('2026-09-12'),
    voucher: {
      id: 'v-43',
      voucherNumber: 43,
      receiptImageUrl: null,
      notes: 'Fall fundraiser — cookie dough',
      createdAt: new Date('2026-09-12'),
      updatedAt: new Date('2026-09-12'),
    },
  },
  {
    id: 'demo-44',
    date: new Date('2026-09-15'),
    category: 'Interest Checking (D)',
    voucherNumber: 44,
    vendor: 'First National Bank',
    amount: 14.65,
    type: 'DEPOSIT',
    cleared: true,
    notes: null,
    receipts: [],
    createdAt: new Date('2026-09-15'),
    updatedAt: new Date('2026-09-15'),
    voucher: {
      id: 'v-44',
      voucherNumber: 44,
      receiptImageUrl: null,
      notes: 'Monthly interest credit',
      createdAt: new Date('2026-09-15'),
      updatedAt: new Date('2026-09-15'),
    },
  },
  {
    id: 'demo-45',
    date: new Date('2026-09-18'),
    category: 'Other (D)',
    voucherNumber: 45,
    vendor: 'Car Wash',
    amount: 390.0,
    type: 'DEPOSIT',
    cleared: true,
    notes: null,
    receipts: [],
    createdAt: new Date('2026-09-18'),
    updatedAt: new Date('2026-09-18'),
    voucher: {
      id: 'v-45',
      voucherNumber: 45,
      receiptImageUrl: null,
      notes: 'Community car wash',
      createdAt: new Date('2026-09-18'),
      updatedAt: new Date('2026-09-18'),
    },
  },
  {
    id: 'demo-46',
    date: new Date('2026-09-22'),
    category: 'Credit Card Machine (D)',
    voucherNumber: 46,
    vendor: 'Square Processing',
    amount: 445.0,
    type: 'DEPOSIT',
    cleared: true,
    notes: null,
    receipts: [],
    createdAt: new Date('2026-09-22'),
    updatedAt: new Date('2026-09-22'),
    voucher: {
      id: 'v-46',
      voucherNumber: 46,
      receiptImageUrl: null,
      notes: 'Credit card batch — September events',
      createdAt: new Date('2026-09-22'),
      updatedAt: new Date('2026-09-22'),
    },
  },
  {
    id: 'demo-47',
    date: new Date('2026-09-08'),
    category: 'Concessions (W)',
    voucherNumber: 47,
    vendor: "Sam's Club",
    amount: 425.0,
    type: 'WITHDRAWAL',
    cleared: true,
    notes: null,
    receipts: [],
    createdAt: new Date('2026-09-08'),
    updatedAt: new Date('2026-09-08'),
    voucher: {
      id: 'v-47',
      voucherNumber: 47,
      receiptImageUrl: null,
      notes: 'Football concession supplies',
      createdAt: new Date('2026-09-08'),
      updatedAt: new Date('2026-09-08'),
    },
  },
  {
    id: 'demo-48',
    date: new Date('2026-09-20'),
    category: 'Interest Checking (W)',
    voucherNumber: 48,
    vendor: 'First National Bank',
    amount: 5.0,
    type: 'WITHDRAWAL',
    cleared: true,
    notes: null,
    receipts: [],
    createdAt: new Date('2026-09-20'),
    updatedAt: new Date('2026-09-20'),
    voucher: {
      id: 'v-48',
      voucherNumber: 48,
      receiptImageUrl: null,
      notes: 'Monthly account service fee',
      createdAt: new Date('2026-09-20'),
      updatedAt: new Date('2026-09-20'),
    },
  },
  {
    id: 'demo-49',
    date: new Date('2026-09-25'),
    category: 'Other (W)',
    voucherNumber: 49,
    vendor: 'Staples',
    amount: 210.0,
    type: 'WITHDRAWAL',
    cleared: true,
    notes: null,
    receipts: [],
    createdAt: new Date('2026-09-25'),
    updatedAt: new Date('2026-09-25'),
    voucher: {
      id: 'v-49',
      voucherNumber: 49,
      receiptImageUrl: null,
      notes: 'Homecoming programs',
      createdAt: new Date('2026-09-25'),
      updatedAt: new Date('2026-09-25'),
    },
  },
  {
    id: 'demo-50',
    date: new Date('2026-09-28'),
    category: 'Director of Band (W)',
    voucherNumber: 50,
    vendor: 'Wenger Corp',
    amount: 1650.0,
    type: 'WITHDRAWAL',
    cleared: false,
    notes: null,
    receipts: [],
    createdAt: new Date('2026-09-28'),
    updatedAt: new Date('2026-09-28'),
    voucher: {
      id: 'v-50',
      voucherNumber: 50,
      receiptImageUrl: null,
      notes: 'Equipment repair and maintenance',
      createdAt: new Date('2026-09-28'),
      updatedAt: new Date('2026-09-28'),
    },
  },

  // ========================================
  // OCTOBER 2026
  // ========================================
  {
    id: 'demo-51',
    date: new Date('2026-10-02'),
    category: 'Concessions (D)',
    voucherNumber: 51,
    vendor: 'Homecoming Game Sales',
    amount: 1650.0,
    type: 'DEPOSIT',
    cleared: true,
    notes: null,
    receipts: [],
    createdAt: new Date('2026-10-02'),
    updatedAt: new Date('2026-10-02'),
    voucher: {
      id: 'v-51',
      voucherNumber: 51,
      receiptImageUrl: null,
      notes: 'Homecoming game — sold out!',
      createdAt: new Date('2026-10-02'),
      updatedAt: new Date('2026-10-02'),
    },
  },
  {
    id: 'demo-52',
    date: new Date('2026-10-08'),
    category: 'Donations (D)',
    voucherNumber: 52,
    vendor: 'Community Foundation',
    amount: 2000.0,
    type: 'DEPOSIT',
    cleared: true,
    notes: null,
    receipts: [],
    createdAt: new Date('2026-10-08'),
    updatedAt: new Date('2026-10-08'),
    voucher: {
      id: 'v-52',
      voucherNumber: 52,
      receiptImageUrl: null,
      notes: 'Fall grant for music education',
      createdAt: new Date('2026-10-08'),
      updatedAt: new Date('2026-10-08'),
    },
  },
  {
    id: 'demo-53',
    date: new Date('2026-10-12'),
    category: 'Fundraiser (D)',
    voucherNumber: 53,
    vendor: 'Pizza Sales',
    amount: 520.0,
    type: 'DEPOSIT',
    cleared: true,
    notes: null,
    receipts: [],
    createdAt: new Date('2026-10-12'),
    updatedAt: new Date('2026-10-12'),
    voucher: {
      id: 'v-53',
      voucherNumber: 53,
      receiptImageUrl: null,
      notes: 'Pizza fundraiser week',
      createdAt: new Date('2026-10-12'),
      updatedAt: new Date('2026-10-12'),
    },
  },
  {
    id: 'demo-54',
    date: new Date('2026-10-15'),
    category: 'Interest Checking (D)',
    voucherNumber: 54,
    vendor: 'First National Bank',
    amount: 15.42,
    type: 'DEPOSIT',
    cleared: true,
    notes: null,
    receipts: [],
    createdAt: new Date('2026-10-15'),
    updatedAt: new Date('2026-10-15'),
    voucher: {
      id: 'v-54',
      voucherNumber: 54,
      receiptImageUrl: null,
      notes: 'Monthly interest credit',
      createdAt: new Date('2026-10-15'),
      updatedAt: new Date('2026-10-15'),
    },
  },
  {
    id: 'demo-55',
    date: new Date('2026-10-18'),
    category: 'Other (D)',
    voucherNumber: 55,
    vendor: 'Tag Sale',
    amount: 480.0,
    type: 'DEPOSIT',
    cleared: true,
    notes: null,
    receipts: [],
    createdAt: new Date('2026-10-18'),
    updatedAt: new Date('2026-10-18'),
    voucher: {
      id: 'v-55',
      voucherNumber: 55,
      receiptImageUrl: null,
      notes: 'Uniform and equipment tag sale',
      createdAt: new Date('2026-10-18'),
      updatedAt: new Date('2026-10-18'),
    },
  },
  {
    id: 'demo-56',
    date: new Date('2026-10-22'),
    category: 'Credit Card Machine (D)',
    voucherNumber: 56,
    vendor: 'Square Processing',
    amount: 580.0,
    type: 'DEPOSIT',
    cleared: true,
    notes: null,
    receipts: [],
    createdAt: new Date('2026-10-22'),
    updatedAt: new Date('2026-10-22'),
    voucher: {
      id: 'v-56',
      voucherNumber: 56,
      receiptImageUrl: null,
      notes: 'Credit card batch — October events',
      createdAt: new Date('2026-10-22'),
      updatedAt: new Date('2026-10-22'),
    },
  },
  {
    id: 'demo-57',
    date: new Date('2026-10-05'),
    category: 'Concessions (W)',
    voucherNumber: 57,
    vendor: 'Sysco Food Services',
    amount: 525.75,
    type: 'WITHDRAWAL',
    cleared: true,
    notes: null,
    receipts: [],
    createdAt: new Date('2026-10-05'),
    updatedAt: new Date('2026-10-05'),
    voucher: {
      id: 'v-57',
      voucherNumber: 57,
      receiptImageUrl: null,
      notes: 'Homecoming week supplies',
      createdAt: new Date('2026-10-05'),
      updatedAt: new Date('2026-10-05'),
    },
  },
  {
    id: 'demo-58',
    date: new Date('2026-10-20'),
    category: 'Interest Checking (W)',
    voucherNumber: 58,
    vendor: 'First National Bank',
    amount: 5.0,
    type: 'WITHDRAWAL',
    cleared: true,
    notes: null,
    receipts: [],
    createdAt: new Date('2026-10-20'),
    updatedAt: new Date('2026-10-20'),
    voucher: {
      id: 'v-58',
      voucherNumber: 58,
      receiptImageUrl: null,
      notes: 'Monthly account service fee',
      createdAt: new Date('2026-10-20'),
      updatedAt: new Date('2026-10-20'),
    },
  },
  {
    id: 'demo-59',
    date: new Date('2026-10-25'),
    category: 'Other (W)',
    voucherNumber: 59,
    vendor: 'Office Depot',
    amount: 178.5,
    type: 'WITHDRAWAL',
    cleared: true,
    notes: null,
    receipts: [],
    createdAt: new Date('2026-10-25'),
    updatedAt: new Date('2026-10-25'),
    voucher: {
      id: 'v-59',
      voucherNumber: 59,
      receiptImageUrl: null,
      notes: 'Competition materials',
      createdAt: new Date('2026-10-25'),
      updatedAt: new Date('2026-10-25'),
    },
  },
  {
    id: 'demo-60',
    date: new Date('2026-10-28'),
    category: 'Director of Band (W)',
    voucherNumber: 60,
    vendor: 'Samuel Ash Music',
    amount: 2100.0,
    type: 'WITHDRAWAL',
    cleared: false,
    notes: null,
    receipts: [],
    createdAt: new Date('2026-10-28'),
    updatedAt: new Date('2026-10-28'),
    voucher: {
      id: 'v-60',
      voucherNumber: 60,
      receiptImageUrl: null,
      notes: 'Marching band show music and drill',
      createdAt: new Date('2026-10-28'),
      updatedAt: new Date('2026-10-28'),
    },
  },

  // ========================================
  // NOVEMBER 2026
  // ========================================
  {
    id: 'demo-61',
    date: new Date('2026-11-05'),
    category: 'Concessions (D)',
    voucherNumber: 61,
    vendor: 'Thanksgiving Tournament Sales',
    amount: 1420.0,
    type: 'DEPOSIT',
    cleared: true,
    notes: null,
    receipts: [],
    createdAt: new Date('2026-11-05'),
    updatedAt: new Date('2026-11-05'),
    voucher: {
      id: 'v-61',
      voucherNumber: 61,
      receiptImageUrl: null,
      notes: 'Thanksgiving basketball tournament',
      createdAt: new Date('2026-11-05'),
      updatedAt: new Date('2026-11-05'),
    },
  },
  {
    id: 'demo-62',
    date: new Date('2026-11-10'),
    category: 'Donations (D)',
    voucherNumber: 62,
    vendor: 'Local Business Sponsorship',
    amount: 1000.0,
    type: 'DEPOSIT',
    cleared: true,
    notes: null,
    receipts: [],
    createdAt: new Date('2026-11-10'),
    updatedAt: new Date('2026-11-10'),
    voucher: {
      id: 'v-62',
      voucherNumber: 62,
      receiptImageUrl: null,
      notes: 'Winter sponsorship',
      createdAt: new Date('2026-11-10'),
      updatedAt: new Date('2026-11-10'),
    },
  },
  {
    id: 'demo-63',
    date: new Date('2026-11-14'),
    category: 'Fundraiser (D)',
    voucherNumber: 63,
    vendor: 'Wreath Sales',
    amount: 780.0,
    type: 'DEPOSIT',
    cleared: true,
    notes: null,
    receipts: [],
    createdAt: new Date('2026-11-14'),
    updatedAt: new Date('2026-11-14'),
    voucher: {
      id: 'v-63',
      voucherNumber: 63,
      receiptImageUrl: null,
      notes: 'Holiday wreath fundraiser',
      createdAt: new Date('2026-11-14'),
      updatedAt: new Date('2026-11-14'),
    },
  },
  {
    id: 'demo-64',
    date: new Date('2026-11-15'),
    category: 'Interest Checking (D)',
    voucherNumber: 64,
    vendor: 'First National Bank',
    amount: 16.28,
    type: 'DEPOSIT',
    cleared: true,
    notes: null,
    receipts: [],
    createdAt: new Date('2026-11-15'),
    updatedAt: new Date('2026-11-15'),
    voucher: {
      id: 'v-64',
      voucherNumber: 64,
      receiptImageUrl: null,
      notes: 'Monthly interest credit',
      createdAt: new Date('2026-11-15'),
      updatedAt: new Date('2026-11-15'),
    },
  },
  {
    id: 'demo-65',
    date: new Date('2026-11-18'),
    category: 'Other (D)',
    voucherNumber: 65,
    vendor: 'Winter Concert Tickets',
    amount: 380.0,
    type: 'DEPOSIT',
    cleared: true,
    notes: null,
    receipts: [],
    createdAt: new Date('2026-11-18'),
    updatedAt: new Date('2026-11-18'),
    voucher: {
      id: 'v-65',
      voucherNumber: 65,
      receiptImageUrl: null,
      notes: 'Winter concert ticket sales',
      createdAt: new Date('2026-11-18'),
      updatedAt: new Date('2026-11-18'),
    },
  },
  {
    id: 'demo-66',
    date: new Date('2026-11-22'),
    category: 'Credit Card Machine (D)',
    voucherNumber: 66,
    vendor: 'Square Processing',
    amount: 490.0,
    type: 'DEPOSIT',
    cleared: true,
    notes: null,
    receipts: [],
    createdAt: new Date('2026-11-22'),
    updatedAt: new Date('2026-11-22'),
    voucher: {
      id: 'v-66',
      voucherNumber: 66,
      receiptImageUrl: null,
      notes: 'Credit card batch — November events',
      createdAt: new Date('2026-11-22'),
      updatedAt: new Date('2026-11-22'),
    },
  },
  {
    id: 'demo-67',
    date: new Date('2026-11-05'),
    category: 'Concessions (W)',
    voucherNumber: 67,
    vendor: 'Coca-Cola Distributing',
    amount: 365.0,
    type: 'WITHDRAWAL',
    cleared: true,
    notes: null,
    receipts: [],
    createdAt: new Date('2026-11-05'),
    updatedAt: new Date('2026-11-05'),
    voucher: {
      id: 'v-67',
      voucherNumber: 67,
      receiptImageUrl: null,
      notes: 'Tournament beverage order',
      createdAt: new Date('2026-11-05'),
      updatedAt: new Date('2026-11-05'),
    },
  },
  {
    id: 'demo-68',
    date: new Date('2026-11-20'),
    category: 'Interest Checking (W)',
    voucherNumber: 68,
    vendor: 'First National Bank',
    amount: 5.0,
    type: 'WITHDRAWAL',
    cleared: true,
    notes: null,
    receipts: [],
    createdAt: new Date('2026-11-20'),
    updatedAt: new Date('2026-11-20'),
    voucher: {
      id: 'v-68',
      voucherNumber: 68,
      receiptImageUrl: null,
      notes: 'Monthly account service fee',
      createdAt: new Date('2026-11-20'),
      updatedAt: new Date('2026-11-20'),
    },
  },
  {
    id: 'demo-69',
    date: new Date('2026-11-25'),
    category: 'Other (W)',
    voucherNumber: 69,
    vendor: 'FedEx',
    amount: 125.0,
    type: 'WITHDRAWAL',
    cleared: true,
    notes: null,
    receipts: [],
    createdAt: new Date('2026-11-25'),
    updatedAt: new Date('2026-11-25'),
    voucher: {
      id: 'v-69',
      voucherNumber: 69,
      receiptImageUrl: null,
      notes: 'Shipping for competition entries',
      createdAt: new Date('2026-11-25'),
      updatedAt: new Date('2026-11-25'),
    },
  },
  {
    id: 'demo-70',
    date: new Date('2026-11-28'),
    category: 'Director of Band (W)',
    voucherNumber: 70,
    vendor: 'Hal Leonard Music',
    amount: 1125.0,
    type: 'WITHDRAWAL',
    cleared: true,
    notes: null,
    receipts: [],
    createdAt: new Date('2026-11-28'),
    updatedAt: new Date('2026-11-28'),
    voucher: {
      id: 'v-70',
      voucherNumber: 70,
      receiptImageUrl: null,
      notes: 'Holiday concert music order',
      createdAt: new Date('2026-11-28'),
      updatedAt: new Date('2026-11-28'),
    },
  },

  // ========================================
  // DECEMBER 2026
  // ========================================
  {
    id: 'demo-71',
    date: new Date('2026-12-05'),
    category: 'Concessions (D)',
    voucherNumber: 71,
    vendor: 'Holiday Tournament Sales',
    amount: 1100.0,
    type: 'DEPOSIT',
    cleared: true,
    notes: null,
    receipts: [],
    createdAt: new Date('2026-12-05'),
    updatedAt: new Date('2026-12-05'),
    voucher: {
      id: 'v-71',
      voucherNumber: 71,
      receiptImageUrl: null,
      notes: 'Holiday basketball tournament',
      createdAt: new Date('2026-12-05'),
      updatedAt: new Date('2026-12-05'),
    },
  },
  {
    id: 'demo-72',
    date: new Date('2026-12-08'),
    category: 'Donations (D)',
    voucherNumber: 72,
    vendor: 'Winter Gala Sponsors',
    amount: 3000.0,
    type: 'DEPOSIT',
    cleared: true,
    notes: null,
    receipts: [],
    createdAt: new Date('2026-12-08'),
    updatedAt: new Date('2026-12-08'),
    voucher: {
      id: 'v-72',
      voucherNumber: 72,
      receiptImageUrl: null,
      notes: 'Winter gala corporate sponsors',
      createdAt: new Date('2026-12-08'),
      updatedAt: new Date('2026-12-08'),
    },
  },
  {
    id: 'demo-73',
    date: new Date('2026-12-12'),
    category: 'Fundraiser (D)',
    voucherNumber: 73,
    vendor: 'Chocolate Bar Sales',
    amount: 650.0,
    type: 'DEPOSIT',
    cleared: true,
    notes: null,
    receipts: [],
    createdAt: new Date('2026-12-12'),
    updatedAt: new Date('2026-12-12'),
    voucher: {
      id: 'v-73',
      voucherNumber: 73,
      receiptImageUrl: null,
      notes: 'Holiday chocolate fundraiser',
      createdAt: new Date('2026-12-12'),
      updatedAt: new Date('2026-12-12'),
    },
  },
  {
    id: 'demo-74',
    date: new Date('2026-12-15'),
    category: 'Interest Checking (D)',
    voucherNumber: 74,
    vendor: 'First National Bank',
    amount: 17.55,
    type: 'DEPOSIT',
    cleared: true,
    notes: null,
    receipts: [],
    createdAt: new Date('2026-12-15'),
    updatedAt: new Date('2026-12-15'),
    voucher: {
      id: 'v-74',
      voucherNumber: 74,
      receiptImageUrl: null,
      notes: 'Monthly interest credit',
      createdAt: new Date('2026-12-15'),
      updatedAt: new Date('2026-12-15'),
    },
  },
  {
    id: 'demo-75',
    date: new Date('2026-12-18'),
    category: 'Other (D)',
    voucherNumber: 75,
    vendor: 'Cookie Exchange',
    amount: 220.0,
    type: 'DEPOSIT',
    cleared: true,
    notes: null,
    receipts: [],
    createdAt: new Date('2026-12-18'),
    updatedAt: new Date('2026-12-18'),
    voucher: {
      id: 'v-75',
      voucherNumber: 75,
      receiptImageUrl: null,
      notes: 'Holiday cookie exchange proceeds',
      createdAt: new Date('2026-12-18'),
      updatedAt: new Date('2026-12-18'),
    },
  },
  {
    id: 'demo-76',
    date: new Date('2026-12-22'),
    category: 'Credit Card Machine (D)',
    voucherNumber: 76,
    vendor: 'Square Processing',
    amount: 350.0,
    type: 'DEPOSIT',
    cleared: true,
    notes: null,
    receipts: [],
    createdAt: new Date('2026-12-22'),
    updatedAt: new Date('2026-12-22'),
    voucher: {
      id: 'v-76',
      voucherNumber: 76,
      receiptImageUrl: null,
      notes: 'Credit card batch — December events',
      createdAt: new Date('2026-12-22'),
      updatedAt: new Date('2026-12-22'),
    },
  },
  {
    id: 'demo-77',
    date: new Date('2026-12-05'),
    category: 'Concessions (W)',
    voucherNumber: 77,
    vendor: "Sam's Club",
    amount: 780.0,
    type: 'WITHDRAWAL',
    cleared: true,
    notes: null,
    receipts: [],
    createdAt: new Date('2026-12-05'),
    updatedAt: new Date('2026-12-05'),
    voucher: {
      id: 'v-77',
      voucherNumber: 77,
      receiptImageUrl: null,
      notes: 'Holiday tournament concessions stock',
      createdAt: new Date('2026-12-05'),
      updatedAt: new Date('2026-12-05'),
    },
  },
  {
    id: 'demo-78',
    date: new Date('2026-12-20'),
    category: 'Interest Checking (W)',
    voucherNumber: 78,
    vendor: 'First National Bank',
    amount: 5.0,
    type: 'WITHDRAWAL',
    cleared: true,
    notes: null,
    receipts: [],
    createdAt: new Date('2026-12-20'),
    updatedAt: new Date('2026-12-20'),
    voucher: {
      id: 'v-78',
      voucherNumber: 78,
      receiptImageUrl: null,
      notes: 'Monthly account service fee',
      createdAt: new Date('2026-12-20'),
      updatedAt: new Date('2026-12-20'),
    },
  },
  {
    id: 'demo-79',
    date: new Date('2026-12-28'),
    category: 'Other (W)',
    voucherNumber: 79,
    vendor: 'Office Depot',
    amount: 245.0,
    type: 'WITHDRAWAL',
    cleared: true,
    notes: null,
    receipts: [],
    createdAt: new Date('2026-12-28'),
    updatedAt: new Date('2026-12-28'),
    voucher: {
      id: 'v-79',
      voucherNumber: 79,
      receiptImageUrl: null,
      notes: 'New year program printing',
      createdAt: new Date('2026-12-28'),
      updatedAt: new Date('2026-12-28'),
    },
  },
  {
    id: 'demo-80',
    date: new Date('2026-12-30'),
    category: 'Director of Band (W)',
    voucherNumber: 80,
    vendor: 'Midwest Music Supply',
    amount: 1450.0,
    type: 'WITHDRAWAL',
    cleared: false,
    notes: null,
    receipts: [],
    createdAt: new Date('2026-12-30'),
    updatedAt: new Date('2026-12-30'),
    voucher: {
      id: 'v-80',
      voucherNumber: 80,
      receiptImageUrl: null,
      notes: 'New instrument order for spring',
      createdAt: new Date('2026-12-30'),
      updatedAt: new Date('2026-12-30'),
    },
  },

  // ========================================
  // JANUARY 2027
  // ========================================
  {
    id: 'demo-81',
    date: new Date('2027-01-05'),
    category: 'Concessions (D)',
    voucherNumber: 81,
    vendor: 'Basketball Game Sales',
    amount: 465.5,
    type: 'DEPOSIT',
    cleared: true,
    notes: null,
    receipts: [],
    createdAt: new Date('2027-01-05'),
    updatedAt: new Date('2027-01-05'),
    voucher: {
      id: 'v-81',
      voucherNumber: 81,
      receiptImageUrl: null,
      notes: 'January basketball home game',
      createdAt: new Date('2027-01-05'),
      updatedAt: new Date('2027-01-05'),
    },
  },
  {
    id: 'demo-82',
    date: new Date('2027-01-08'),
    category: 'Donations (D)',
    voucherNumber: 82,
    vendor: 'Alumni Association',
    amount: 1800.0,
    type: 'DEPOSIT',
    cleared: true,
    notes: null,
    receipts: [],
    createdAt: new Date('2027-01-08'),
    updatedAt: new Date('2027-01-08'),
    voucher: {
      id: 'v-82',
      voucherNumber: 82,
      receiptImageUrl: null,
      notes: 'Annual alumni donation',
      createdAt: new Date('2027-01-08'),
      updatedAt: new Date('2027-01-08'),
    },
  },
  {
    id: 'demo-83',
    date: new Date('2027-01-12'),
    category: 'Fundraiser (D)',
    voucherNumber: 83,
    vendor: 'Cookie Dough Sales',
    amount: 920.0,
    type: 'DEPOSIT',
    cleared: true,
    notes: null,
    receipts: [],
    createdAt: new Date('2027-01-12'),
    updatedAt: new Date('2027-01-12'),
    voucher: {
      id: 'v-83',
      voucherNumber: 83,
      receiptImageUrl: null,
      notes: 'Winter fundraiser',
      createdAt: new Date('2027-01-12'),
      updatedAt: new Date('2027-01-12'),
    },
  },
  {
    id: 'demo-84',
    date: new Date('2027-01-15'),
    category: 'Interest Checking (D)',
    voucherNumber: 84,
    vendor: 'First National Bank',
    amount: 18.75,
    type: 'DEPOSIT',
    cleared: true,
    notes: null,
    receipts: [],
    createdAt: new Date('2027-01-15'),
    updatedAt: new Date('2027-01-15'),
    voucher: {
      id: 'v-84',
      voucherNumber: 84,
      receiptImageUrl: null,
      notes: 'Monthly interest credit',
      createdAt: new Date('2027-01-15'),
      updatedAt: new Date('2027-01-15'),
    },
  },
  {
    id: 'demo-85',
    date: new Date('2027-01-18'),
    category: 'Other (D)',
    voucherNumber: 85,
    vendor: 'Car Wash',
    amount: 380.0,
    type: 'DEPOSIT',
    cleared: true,
    notes: null,
    receipts: [],
    createdAt: new Date('2027-01-18'),
    updatedAt: new Date('2027-01-18'),
    voucher: {
      id: 'v-85',
      voucherNumber: 85,
      receiptImageUrl: null,
      notes: 'Winter car wash',
      createdAt: new Date('2027-01-18'),
      updatedAt: new Date('2027-01-18'),
    },
  },
  {
    id: 'demo-86',
    date: new Date('2027-01-22'),
    category: 'Credit Card Machine (D)',
    voucherNumber: 86,
    vendor: 'Square Processing',
    amount: 295.0,
    type: 'DEPOSIT',
    cleared: true,
    notes: null,
    receipts: [],
    createdAt: new Date('2027-01-22'),
    updatedAt: new Date('2027-01-22'),
    voucher: {
      id: 'v-86',
      voucherNumber: 86,
      receiptImageUrl: null,
      notes: 'Credit card batch — January',
      createdAt: new Date('2027-01-22'),
      updatedAt: new Date('2027-01-22'),
    },
  },
  {
    id: 'demo-87',
    date: new Date('2027-01-10'),
    category: 'Concessions (W)',
    voucherNumber: 87,
    vendor: 'Sysco Food Services',
    amount: 335.0,
    type: 'WITHDRAWAL',
    cleared: true,
    notes: null,
    receipts: [],
    createdAt: new Date('2027-01-10'),
    updatedAt: new Date('2027-01-10'),
    voucher: {
      id: 'v-87',
      voucherNumber: 87,
      receiptImageUrl: null,
      notes: 'Concession supplies restock',
      createdAt: new Date('2027-01-10'),
      updatedAt: new Date('2027-01-10'),
    },
  },
  {
    id: 'demo-88',
    date: new Date('2027-01-20'),
    category: 'Interest Checking (W)',
    voucherNumber: 88,
    vendor: 'First National Bank',
    amount: 5.0,
    type: 'WITHDRAWAL',
    cleared: true,
    notes: null,
    receipts: [],
    createdAt: new Date('2027-01-20'),
    updatedAt: new Date('2027-01-20'),
    voucher: {
      id: 'v-88',
      voucherNumber: 88,
      receiptImageUrl: null,
      notes: 'Monthly account service fee',
      createdAt: new Date('2027-01-20'),
      updatedAt: new Date('2027-01-20'),
    },
  },
  {
    id: 'demo-89',
    date: new Date('2027-01-25'),
    category: 'Other (W)',
    voucherNumber: 89,
    vendor: 'Staples',
    amount: 165.33,
    type: 'WITHDRAWAL',
    cleared: true,
    notes: null,
    receipts: [],
    createdAt: new Date('2027-01-25'),
    updatedAt: new Date('2027-01-25'),
    voucher: {
      id: 'v-89',
      voucherNumber: 89,
      receiptImageUrl: null,
      notes: 'Office supplies',
      createdAt: new Date('2027-01-25'),
      updatedAt: new Date('2027-01-25'),
    },
  },
  {
    id: 'demo-90',
    date: new Date('2027-01-28'),
    category: 'Director of Band (W)',
    voucherNumber: 90,
    vendor: 'Yamaha Music',
    amount: 1850.0,
    type: 'WITHDRAWAL',
    cleared: false,
    notes: null,
    receipts: [],
    createdAt: new Date('2027-01-28'),
    updatedAt: new Date('2027-01-28'),
    voucher: {
      id: 'v-90',
      voucherNumber: 90,
      receiptImageUrl: null,
      notes: 'Instrument repair - woodwinds',
      createdAt: new Date('2027-01-28'),
      updatedAt: new Date('2027-01-28'),
    },
  },

  // ========================================
  // FEBRUARY 2027
  // ========================================
  {
    id: 'demo-91',
    date: new Date('2027-02-02'),
    category: 'Concessions (D)',
    voucherNumber: 91,
    vendor: 'Wrestling Tournament Sales',
    amount: 620.0,
    type: 'DEPOSIT',
    cleared: true,
    notes: null,
    receipts: [],
    createdAt: new Date('2027-02-02'),
    updatedAt: new Date('2027-02-02'),
    voucher: {
      id: 'v-91',
      voucherNumber: 91,
      receiptImageUrl: null,
      notes: 'Wrestling tournament concessions',
      createdAt: new Date('2027-02-02'),
      updatedAt: new Date('2027-02-02'),
    },
  },
  {
    id: 'demo-92',
    date: new Date('2027-02-05'),
    category: 'Donations (D)',
    voucherNumber: 92,
    vendor: 'Smith Auto Repair',
    amount: 800.0,
    type: 'DEPOSIT',
    cleared: true,
    notes: null,
    receipts: [],
    createdAt: new Date('2027-02-05'),
    updatedAt: new Date('2027-02-05'),
    voucher: {
      id: 'v-92',
      voucherNumber: 92,
      receiptImageUrl: null,
      notes: 'Valentine sponsorship',
      createdAt: new Date('2027-02-05'),
      updatedAt: new Date('2027-02-05'),
    },
  },
  {
    id: 'demo-93',
    date: new Date('2027-02-10'),
    category: 'Fundraiser (D)',
    voucherNumber: 93,
    vendor: 'Valentine Candy Sales',
    amount: 1180.0,
    type: 'DEPOSIT',
    cleared: true,
    notes: null,
    receipts: [],
    createdAt: new Date('2027-02-10'),
    updatedAt: new Date('2027-02-10'),
    voucher: {
      id: 'v-93',
      voucherNumber: 93,
      receiptImageUrl: null,
      notes: 'Valentine fundraiser — candy grams',
      createdAt: new Date('2027-02-10'),
      updatedAt: new Date('2027-02-10'),
    },
  },
  {
    id: 'demo-94',
    date: new Date('2027-02-14'),
    category: 'Interest Checking (D)',
    voucherNumber: 94,
    vendor: 'First National Bank',
    amount: 19.22,
    type: 'DEPOSIT',
    cleared: true,
    notes: null,
    receipts: [],
    createdAt: new Date('2027-02-14'),
    updatedAt: new Date('2027-02-14'),
    voucher: {
      id: 'v-94',
      voucherNumber: 94,
      receiptImageUrl: null,
      notes: 'Monthly interest credit',
      createdAt: new Date('2027-02-14'),
      updatedAt: new Date('2027-02-14'),
    },
  },
  {
    id: 'demo-95',
    date: new Date('2027-02-18'),
    category: 'Other (D)',
    voucherNumber: 95,
    vendor: 'Garage Sale',
    amount: 420.0,
    type: 'DEPOSIT',
    cleared: true,
    notes: null,
    receipts: [],
    createdAt: new Date('2027-02-18'),
    updatedAt: new Date('2027-02-18'),
    voucher: {
      id: 'v-95',
      voucherNumber: 95,
      receiptImageUrl: null,
      notes: 'Band family garage sale',
      createdAt: new Date('2027-02-18'),
      updatedAt: new Date('2027-02-18'),
    },
  },
  {
    id: 'demo-96',
    date: new Date('2027-02-22'),
    category: 'Credit Card Machine (D)',
    voucherNumber: 96,
    vendor: 'Square Processing',
    amount: 410.0,
    type: 'DEPOSIT',
    cleared: true,
    notes: null,
    receipts: [],
    createdAt: new Date('2027-02-22'),
    updatedAt: new Date('2027-02-22'),
    voucher: {
      id: 'v-96',
      voucherNumber: 96,
      receiptImageUrl: null,
      notes: 'Credit card batch — February',
      createdAt: new Date('2027-02-22'),
      updatedAt: new Date('2027-02-22'),
    },
  },
  {
    id: 'demo-97',
    date: new Date('2027-02-08'),
    category: 'Concessions (W)',
    voucherNumber: 97,
    vendor: "Sam's Club",
    amount: 445.0,
    type: 'WITHDRAWAL',
    cleared: true,
    notes: null,
    receipts: [],
    createdAt: new Date('2027-02-08'),
    updatedAt: new Date('2027-02-08'),
    voucher: {
      id: 'v-97',
      voucherNumber: 97,
      receiptImageUrl: null,
      notes: 'Tournament concession supplies',
      createdAt: new Date('2027-02-08'),
      updatedAt: new Date('2027-02-08'),
    },
  },
  {
    id: 'demo-98',
    date: new Date('2027-02-20'),
    category: 'Interest Checking (W)',
    voucherNumber: 98,
    vendor: 'First National Bank',
    amount: 5.0,
    type: 'WITHDRAWAL',
    cleared: true,
    notes: null,
    receipts: [],
    createdAt: new Date('2027-02-20'),
    updatedAt: new Date('2027-02-20'),
    voucher: {
      id: 'v-98',
      voucherNumber: 98,
      receiptImageUrl: null,
      notes: 'Monthly account service fee',
      createdAt: new Date('2027-02-20'),
      updatedAt: new Date('2027-02-20'),
    },
  },
  {
    id: 'demo-99',
    date: new Date('2027-02-24'),
    category: 'Other (W)',
    voucherNumber: 99,
    vendor: 'Office Depot',
    amount: 198.5,
    type: 'WITHDRAWAL',
    cleared: true,
    notes: null,
    receipts: [],
    createdAt: new Date('2027-02-24'),
    updatedAt: new Date('2027-02-24'),
    voucher: {
      id: 'v-99',
      voucherNumber: 99,
      receiptImageUrl: null,
      notes: 'Concert program printing',
      createdAt: new Date('2027-02-24'),
      updatedAt: new Date('2027-02-24'),
    },
  },
  {
    id: 'demo-100',
    date: new Date('2027-02-28'),
    category: 'Director of Band (W)',
    voucherNumber: 100,
    vendor: 'Hal Leonard Music',
    amount: 725.0,
    type: 'WITHDRAWAL',
    cleared: true,
    notes: null,
    receipts: [],
    createdAt: new Date('2027-02-28'),
    updatedAt: new Date('2027-02-28'),
    voucher: {
      id: 'v-100',
      voucherNumber: 100,
      receiptImageUrl: null,
      notes: 'Spring concert sheet music',
      createdAt: new Date('2027-02-28'),
      updatedAt: new Date('2027-02-28'),
    },
  },

  // ========================================
  // MARCH 2027
  // ========================================
  {
    id: 'demo-101',
    date: new Date('2027-03-01'),
    category: 'Concessions (D)',
    voucherNumber: 101,
    vendor: 'State Qualifier Sales',
    amount: 950.0,
    type: 'DEPOSIT',
    cleared: true,
    notes: null,
    receipts: [],
    createdAt: new Date('2027-03-01'),
    updatedAt: new Date('2027-03-01'),
    voucher: {
      id: 'v-101',
      voucherNumber: 101,
      receiptImageUrl: null,
      notes: 'State basketball qualifier',
      createdAt: new Date('2027-03-01'),
      updatedAt: new Date('2027-03-01'),
    },
  },
  {
    id: 'demo-102',
    date: new Date('2027-03-05'),
    category: 'Donations (D)',
    voucherNumber: 102,
    vendor: 'Local Business Sponsorship',
    amount: 1100.0,
    type: 'DEPOSIT',
    cleared: true,
    notes: null,
    receipts: [],
    createdAt: new Date('2027-03-05'),
    updatedAt: new Date('2027-03-05'),
    voucher: {
      id: 'v-102',
      voucherNumber: 102,
      receiptImageUrl: null,
      notes: 'Spring sponsorship',
      createdAt: new Date('2027-03-05'),
      updatedAt: new Date('2027-03-05'),
    },
  },
  {
    id: 'demo-103',
    date: new Date('2027-03-10'),
    category: 'Fundraiser (D)',
    voucherNumber: 103,
    vendor: 'Pizza Sales',
    amount: 580.0,
    type: 'DEPOSIT',
    cleared: true,
    notes: null,
    receipts: [],
    createdAt: new Date('2027-03-10'),
    updatedAt: new Date('2027-03-10'),
    voucher: {
      id: 'v-103',
      voucherNumber: 103,
      receiptImageUrl: null,
      notes: 'Pizza fundraiser week',
      createdAt: new Date('2027-03-10'),
      updatedAt: new Date('2027-03-10'),
    },
  },
  {
    id: 'demo-104',
    date: new Date('2027-03-15'),
    category: 'Interest Checking (D)',
    voucherNumber: 104,
    vendor: 'First National Bank',
    amount: 20.45,
    type: 'DEPOSIT',
    cleared: true,
    notes: null,
    receipts: [],
    createdAt: new Date('2027-03-15'),
    updatedAt: new Date('2027-03-15'),
    voucher: {
      id: 'v-104',
      voucherNumber: 104,
      receiptImageUrl: null,
      notes: 'Monthly interest credit',
      createdAt: new Date('2027-03-15'),
      updatedAt: new Date('2027-03-15'),
    },
  },
  {
    id: 'demo-105',
    date: new Date('2027-03-18'),
    category: 'Other (D)',
    voucherNumber: 105,
    vendor: 'Band Boosters Auction',
    amount: 1350.0,
    type: 'DEPOSIT',
    cleared: true,
    notes: null,
    receipts: [],
    createdAt: new Date('2027-03-18'),
    updatedAt: new Date('2027-03-18'),
    voucher: {
      id: 'v-105',
      voucherNumber: 105,
      receiptImageUrl: null,
      notes: 'Annual silent auction',
      createdAt: new Date('2027-03-18'),
      updatedAt: new Date('2027-03-18'),
    },
  },
  {
    id: 'demo-106',
    date: new Date('2027-03-22'),
    category: 'Credit Card Machine (D)',
    voucherNumber: 106,
    vendor: 'Square Processing',
    amount: 465.0,
    type: 'DEPOSIT',
    cleared: true,
    notes: null,
    receipts: [],
    createdAt: new Date('2027-03-22'),
    updatedAt: new Date('2027-03-22'),
    voucher: {
      id: 'v-106',
      voucherNumber: 106,
      receiptImageUrl: null,
      notes: 'Credit card batch — March',
      createdAt: new Date('2027-03-22'),
      updatedAt: new Date('2027-03-22'),
    },
  },
  {
    id: 'demo-107',
    date: new Date('2027-03-08'),
    category: 'Concessions (W)',
    voucherNumber: 107,
    vendor: 'Coca-Cola Distributing',
    amount: 295.0,
    type: 'WITHDRAWAL',
    cleared: true,
    notes: null,
    receipts: [],
    createdAt: new Date('2027-03-08'),
    updatedAt: new Date('2027-03-08'),
    voucher: {
      id: 'v-107',
      voucherNumber: 107,
      receiptImageUrl: null,
      notes: 'Beverage order for games',
      createdAt: new Date('2027-03-08'),
      updatedAt: new Date('2027-03-08'),
    },
  },
  {
    id: 'demo-108',
    date: new Date('2027-03-20'),
    category: 'Interest Checking (W)',
    voucherNumber: 108,
    vendor: 'First National Bank',
    amount: 5.0,
    type: 'WITHDRAWAL',
    cleared: true,
    notes: null,
    receipts: [],
    createdAt: new Date('2027-03-20'),
    updatedAt: new Date('2027-03-20'),
    voucher: {
      id: 'v-108',
      voucherNumber: 108,
      receiptImageUrl: null,
      notes: 'Monthly account service fee',
      createdAt: new Date('2027-03-20'),
      updatedAt: new Date('2027-03-20'),
    },
  },
  {
    id: 'demo-109',
    date: new Date('2027-03-25'),
    category: 'Other (W)',
    voucherNumber: 109,
    vendor: 'FedEx',
    amount: 95.99,
    type: 'WITHDRAWAL',
    cleared: true,
    notes: null,
    receipts: [],
    createdAt: new Date('2027-03-25'),
    updatedAt: new Date('2027-03-25'),
    voucher: {
      id: 'v-109',
      voucherNumber: 109,
      receiptImageUrl: null,
      notes: 'Shipping for competition',
      createdAt: new Date('2027-03-25'),
      updatedAt: new Date('2027-03-25'),
    },
  },
  {
    id: 'demo-110',
    date: new Date('2027-03-28'),
    category: 'Director of Band (W)',
    voucherNumber: 110,
    vendor: 'Midwest Music Supply',
    amount: 1950.0,
    type: 'WITHDRAWAL',
    cleared: false,
    notes: null,
    receipts: [],
    createdAt: new Date('2027-03-28'),
    updatedAt: new Date('2027-03-28'),
    voucher: {
      id: 'v-110',
      voucherNumber: 110,
      receiptImageUrl: null,
      notes: 'New brass instruments',
      createdAt: new Date('2027-03-28'),
      updatedAt: new Date('2027-03-28'),
    },
  },

  // ========================================
  // APRIL 2027
  // ========================================
  {
    id: 'demo-111',
    date: new Date('2027-04-02'),
    category: 'Concessions (D)',
    voucherNumber: 111,
    vendor: 'Spring Festival Sales',
    amount: 1350.0,
    type: 'DEPOSIT',
    cleared: true,
    notes: null,
    receipts: [],
    createdAt: new Date('2027-04-02'),
    updatedAt: new Date('2027-04-02'),
    voucher: {
      id: 'v-111',
      voucherNumber: 111,
      receiptImageUrl: null,
      notes: 'Spring festival concessions',
      createdAt: new Date('2027-04-02'),
      updatedAt: new Date('2027-04-02'),
    },
  },
  {
    id: 'demo-112',
    date: new Date('2027-04-08'),
    category: 'Donations (D)',
    voucherNumber: 112,
    vendor: 'Community Foundation',
    amount: 2800.0,
    type: 'DEPOSIT',
    cleared: true,
    notes: null,
    receipts: [],
    createdAt: new Date('2027-04-08'),
    updatedAt: new Date('2027-04-08'),
    voucher: {
      id: 'v-112',
      voucherNumber: 112,
      receiptImageUrl: null,
      notes: 'Spring grant for music education',
      createdAt: new Date('2027-04-08'),
      updatedAt: new Date('2027-04-08'),
    },
  },
  {
    id: 'demo-113',
    date: new Date('2027-04-12'),
    category: 'Fundraiser (D)',
    voucherNumber: 113,
    vendor: 'Car Wash',
    amount: 520.0,
    type: 'DEPOSIT',
    cleared: true,
    notes: null,
    receipts: [],
    createdAt: new Date('2027-04-12'),
    updatedAt: new Date('2027-04-12'),
    voucher: {
      id: 'v-113',
      voucherNumber: 113,
      receiptImageUrl: null,
      notes: 'Spring car wash fundraiser',
      createdAt: new Date('2027-04-12'),
      updatedAt: new Date('2027-04-12'),
    },
  },
  {
    id: 'demo-114',
    date: new Date('2027-04-15'),
    category: 'Interest Checking (D)',
    voucherNumber: 114,
    vendor: 'First National Bank',
    amount: 22.18,
    type: 'DEPOSIT',
    cleared: true,
    notes: null,
    receipts: [],
    createdAt: new Date('2027-04-15'),
    updatedAt: new Date('2027-04-15'),
    voucher: {
      id: 'v-114',
      voucherNumber: 114,
      receiptImageUrl: null,
      notes: 'Monthly interest credit',
      createdAt: new Date('2027-04-15'),
      updatedAt: new Date('2027-04-15'),
    },
  },
  {
    id: 'demo-115',
    date: new Date('2027-04-18'),
    category: 'Other (D)',
    voucherNumber: 115,
    vendor: 'Tag Sale',
    amount: 590.0,
    type: 'DEPOSIT',
    cleared: true,
    notes: null,
    receipts: [],
    createdAt: new Date('2027-04-18'),
    updatedAt: new Date('2027-04-18'),
    voucher: {
      id: 'v-115',
      voucherNumber: 115,
      receiptImageUrl: null,
      notes: 'Band uniform tag sale',
      createdAt: new Date('2027-04-18'),
      updatedAt: new Date('2027-04-18'),
    },
  },
  {
    id: 'demo-116',
    date: new Date('2027-04-22'),
    category: 'Credit Card Machine (D)',
    voucherNumber: 116,
    vendor: 'Square Processing',
    amount: 540.0,
    type: 'DEPOSIT',
    cleared: true,
    notes: null,
    receipts: [],
    createdAt: new Date('2027-04-22'),
    updatedAt: new Date('2027-04-22'),
    voucher: {
      id: 'v-116',
      voucherNumber: 116,
      receiptImageUrl: null,
      notes: 'Credit card batch — April',
      createdAt: new Date('2027-04-22'),
      updatedAt: new Date('2027-04-22'),
    },
  },
  {
    id: 'demo-117',
    date: new Date('2027-04-05'),
    category: 'Concessions (W)',
    voucherNumber: 117,
    vendor: "Sam's Club",
    amount: 415.0,
    type: 'WITHDRAWAL',
    cleared: true,
    notes: null,
    receipts: [],
    createdAt: new Date('2027-04-05'),
    updatedAt: new Date('2027-04-05'),
    voucher: {
      id: 'v-117',
      voucherNumber: 117,
      receiptImageUrl: null,
      notes: 'Spring concession supplies',
      createdAt: new Date('2027-04-05'),
      updatedAt: new Date('2027-04-05'),
    },
  },
  {
    id: 'demo-118',
    date: new Date('2027-04-20'),
    category: 'Interest Checking (W)',
    voucherNumber: 118,
    vendor: 'First National Bank',
    amount: 5.0,
    type: 'WITHDRAWAL',
    cleared: true,
    notes: null,
    receipts: [],
    createdAt: new Date('2027-04-20'),
    updatedAt: new Date('2027-04-20'),
    voucher: {
      id: 'v-118',
      voucherNumber: 118,
      receiptImageUrl: null,
      notes: 'Monthly account service fee',
      createdAt: new Date('2027-04-20'),
      updatedAt: new Date('2027-04-20'),
    },
  },
  {
    id: 'demo-119',
    date: new Date('2027-04-25'),
    category: 'Other (W)',
    voucherNumber: 119,
    vendor: 'Amazon',
    amount: 254.99,
    type: 'WITHDRAWAL',
    cleared: true,
    notes: null,
    receipts: [],
    createdAt: new Date('2027-04-25'),
    updatedAt: new Date('2027-04-25'),
    voucher: {
      id: 'v-119',
      voucherNumber: 119,
      receiptImageUrl: null,
      notes: 'Music stands and equipment',
      createdAt: new Date('2027-04-25'),
      updatedAt: new Date('2027-04-25'),
    },
  },
  {
    id: 'demo-120',
    date: new Date('2027-04-28'),
    category: 'Director of Band (W)',
    voucherNumber: 120,
    vendor: 'Samuel Ash Music',
    amount: 1050.0,
    type: 'WITHDRAWAL',
    cleared: false,
    notes: null,
    receipts: [],
    createdAt: new Date('2027-04-28'),
    updatedAt: new Date('2027-04-28'),
    voucher: {
      id: 'v-120',
      voucherNumber: 120,
      receiptImageUrl: null,
      notes: 'Spring concert uniform repairs',
      createdAt: new Date('2027-04-28'),
      updatedAt: new Date('2027-04-28'),
    },
  },

  // ========================================
  // MAY 2027 - Start of FY 2027-2028
  // ========================================
  {
    id: 'demo-121',
    date: new Date('2027-05-03'),
    category: 'Concessions (D)',
    voucherNumber: 121,
    vendor: 'Baseball Game Sales',
    amount: 395.0,
    type: 'DEPOSIT',
    cleared: true,
    notes: null,
    receipts: [],
    createdAt: new Date('2027-05-03'),
    updatedAt: new Date('2027-05-03'),
    voucher: {
      id: 'v-121',
      voucherNumber: 121,
      receiptImageUrl: null,
      notes: 'Baseball home game concessions',
      createdAt: new Date('2027-05-03'),
      updatedAt: new Date('2027-05-03'),
    },
  },
  {
    id: 'demo-122',
    date: new Date('2027-05-08'),
    category: 'Donations (D)',
    voucherNumber: 122,
    vendor: 'Alumni Association',
    amount: 1600.0,
    type: 'DEPOSIT',
    cleared: true,
    notes: null,
    receipts: [],
    createdAt: new Date('2027-05-08'),
    updatedAt: new Date('2027-05-08'),
    voucher: {
      id: 'v-122',
      voucherNumber: 122,
      receiptImageUrl: null,
      notes: 'Annual alumni donation',
      createdAt: new Date('2027-05-08'),
      updatedAt: new Date('2027-05-08'),
    },
  },
  {
    id: 'demo-123',
    date: new Date('2027-05-12'),
    category: 'Fundraiser (D)',
    voucherNumber: 123,
    vendor: 'Spring Auction',
    amount: 2200.0,
    type: 'DEPOSIT',
    cleared: true,
    notes: null,
    receipts: [],
    createdAt: new Date('2027-05-12'),
    updatedAt: new Date('2027-05-12'),
    voucher: {
      id: 'v-123',
      voucherNumber: 123,
      receiptImageUrl: null,
      notes: 'Spring auction proceeds',
      createdAt: new Date('2027-05-12'),
      updatedAt: new Date('2027-05-12'),
    },
  },
  {
    id: 'demo-124',
    date: new Date('2027-05-15'),
    category: 'Interest Checking (D)',
    voucherNumber: 124,
    vendor: 'First National Bank',
    amount: 18.25,
    type: 'DEPOSIT',
    cleared: true,
    notes: null,
    receipts: [],
    createdAt: new Date('2027-05-15'),
    updatedAt: new Date('2027-05-15'),
    voucher: {
      id: 'v-124',
      voucherNumber: 124,
      receiptImageUrl: null,
      notes: 'Monthly interest credit',
      createdAt: new Date('2027-05-15'),
      updatedAt: new Date('2027-05-15'),
    },
  },
  {
    id: 'demo-125',
    date: new Date('2027-05-18'),
    category: 'Other (D)',
    voucherNumber: 125,
    vendor: 'Spring Concert Tickets',
    amount: 480.0,
    type: 'DEPOSIT',
    cleared: true,
    notes: null,
    receipts: [],
    createdAt: new Date('2027-05-18'),
    updatedAt: new Date('2027-05-18'),
    voucher: {
      id: 'v-125',
      voucherNumber: 125,
      receiptImageUrl: null,
      notes: 'Spring concert ticket sales',
      createdAt: new Date('2027-05-18'),
      updatedAt: new Date('2027-05-18'),
    },
  },
  {
    id: 'demo-126',
    date: new Date('2027-05-22'),
    category: 'Credit Card Machine (D)',
    voucherNumber: 126,
    vendor: 'Square Processing',
    amount: 340.0,
    type: 'DEPOSIT',
    cleared: true,
    notes: null,
    receipts: [],
    createdAt: new Date('2027-05-22'),
    updatedAt: new Date('2027-05-22'),
    voucher: {
      id: 'v-126',
      voucherNumber: 126,
      receiptImageUrl: null,
      notes: 'Credit card batch — May events',
      createdAt: new Date('2027-05-22'),
      updatedAt: new Date('2027-05-22'),
    },
  },
  {
    id: 'demo-127',
    date: new Date('2027-05-05'),
    category: 'Concessions (W)',
    voucherNumber: 127,
    vendor: 'Sysco Food Services',
    amount: 325.0,
    type: 'WITHDRAWAL',
    cleared: true,
    notes: null,
    receipts: [],
    createdAt: new Date('2027-05-05'),
    updatedAt: new Date('2027-05-05'),
    voucher: {
      id: 'v-127',
      voucherNumber: 127,
      receiptImageUrl: null,
      notes: 'End of year event supplies',
      createdAt: new Date('2027-05-05'),
      updatedAt: new Date('2027-05-05'),
    },
  },
  {
    id: 'demo-128',
    date: new Date('2027-05-20'),
    category: 'Interest Checking (W)',
    voucherNumber: 128,
    vendor: 'First National Bank',
    amount: 5.0,
    type: 'WITHDRAWAL',
    cleared: true,
    notes: null,
    receipts: [],
    createdAt: new Date('2027-05-20'),
    updatedAt: new Date('2027-05-20'),
    voucher: {
      id: 'v-128',
      voucherNumber: 128,
      receiptImageUrl: null,
      notes: 'Monthly account service fee',
      createdAt: new Date('2027-05-20'),
      updatedAt: new Date('2027-05-20'),
    },
  },
  {
    id: 'demo-129',
    date: new Date('2027-05-25'),
    category: 'Other (W)',
    voucherNumber: 129,
    vendor: 'VFW Hall',
    amount: 325.0,
    type: 'WITHDRAWAL',
    cleared: true,
    notes: null,
    receipts: [],
    createdAt: new Date('2027-05-25'),
    updatedAt: new Date('2027-05-25'),
    voucher: {
      id: 'v-129',
      voucherNumber: 129,
      receiptImageUrl: null,
      notes: 'End of year banquet rental',
      createdAt: new Date('2027-05-25'),
      updatedAt: new Date('2027-05-25'),
    },
  },
  {
    id: 'demo-130',
    date: new Date('2027-05-28'),
    category: 'Director of Band (W)',
    voucherNumber: 130,
    vendor: 'Bands of America',
    amount: 475.0,
    type: 'WITHDRAWAL',
    cleared: true,
    notes: null,
    receipts: [],
    createdAt: new Date('2027-05-28'),
    updatedAt: new Date('2027-05-28'),
    voucher: {
      id: 'v-130',
      voucherNumber: 130,
      receiptImageUrl: null,
      notes: 'Competition registration fee',
      createdAt: new Date('2027-05-28'),
      updatedAt: new Date('2027-05-28'),
    },
  },

  // ========================================
  // JUNE 2027
  // ========================================
  {
    id: 'demo-131',
    date: new Date('2027-06-05'),
    category: 'Concessions (D)',
    voucherNumber: 131,
    vendor: 'Summer Camp Sales',
    amount: 820.0,
    type: 'DEPOSIT',
    cleared: true,
    notes: null,
    receipts: [],
    createdAt: new Date('2027-06-05'),
    updatedAt: new Date('2027-06-05'),
    voucher: {
      id: 'v-131',
      voucherNumber: 131,
      receiptImageUrl: null,
      notes: 'Band summer camp concessions',
      createdAt: new Date('2027-06-05'),
      updatedAt: new Date('2027-06-05'),
    },
  },
  {
    id: 'demo-132',
    date: new Date('2027-06-10'),
    category: 'Donations (D)',
    voucherNumber: 132,
    vendor: 'Parent Association',
    amount: 850.0,
    type: 'DEPOSIT',
    cleared: true,
    notes: null,
    receipts: [],
    createdAt: new Date('2027-06-10'),
    updatedAt: new Date('2027-06-10'),
    voucher: {
      id: 'v-132',
      voucherNumber: 132,
      receiptImageUrl: null,
      notes: 'Summer program funding',
      createdAt: new Date('2027-06-10'),
      updatedAt: new Date('2027-06-10'),
    },
  },
  {
    id: 'demo-133',
    date: new Date('2027-06-15'),
    category: 'Fundraiser (D)',
    voucherNumber: 133,
    vendor: 'Car Wash',
    amount: 340.0,
    type: 'DEPOSIT',
    cleared: true,
    notes: null,
    receipts: [],
    createdAt: new Date('2027-06-15'),
    updatedAt: new Date('2027-06-15'),
    voucher: {
      id: 'v-133',
      voucherNumber: 133,
      receiptImageUrl: null,
      notes: 'Summer car wash',
      createdAt: new Date('2027-06-15'),
      updatedAt: new Date('2027-06-15'),
    },
  },
  {
    id: 'demo-134',
    date: new Date('2027-06-15'),
    category: 'Interest Checking (D)',
    voucherNumber: 134,
    vendor: 'First National Bank',
    amount: 15.85,
    type: 'DEPOSIT',
    cleared: true,
    notes: null,
    receipts: [],
    createdAt: new Date('2027-06-15'),
    updatedAt: new Date('2027-06-15'),
    voucher: {
      id: 'v-134',
      voucherNumber: 134,
      receiptImageUrl: null,
      notes: 'Monthly interest credit',
      createdAt: new Date('2027-06-15'),
      updatedAt: new Date('2027-06-15'),
    },
  },
  {
    id: 'demo-135',
    date: new Date('2027-06-18'),
    category: 'Other (D)',
    voucherNumber: 135,
    vendor: 'Summer Camp Registration',
    amount: 475.0,
    type: 'DEPOSIT',
    cleared: true,
    notes: null,
    receipts: [],
    createdAt: new Date('2027-06-18'),
    updatedAt: new Date('2027-06-18'),
    voucher: {
      id: 'v-135',
      voucherNumber: 135,
      receiptImageUrl: null,
      notes: 'Band summer camp fees',
      createdAt: new Date('2027-06-18'),
      updatedAt: new Date('2027-06-18'),
    },
  },
  {
    id: 'demo-136',
    date: new Date('2027-06-22'),
    category: 'Credit Card Machine (D)',
    voucherNumber: 136,
    vendor: 'Square Processing',
    amount: 295.0,
    type: 'DEPOSIT',
    cleared: true,
    notes: null,
    receipts: [],
    createdAt: new Date('2027-06-22'),
    updatedAt: new Date('2027-06-22'),
    voucher: {
      id: 'v-136',
      voucherNumber: 136,
      receiptImageUrl: null,
      notes: 'Credit card batch — June events',
      createdAt: new Date('2027-06-22'),
      updatedAt: new Date('2027-06-22'),
    },
  },
  {
    id: 'demo-137',
    date: new Date('2027-06-08'),
    category: 'Concessions (W)',
    voucherNumber: 137,
    vendor: "Sam's Club",
    amount: 285.0,
    type: 'WITHDRAWAL',
    cleared: true,
    notes: null,
    receipts: [],
    createdAt: new Date('2027-06-08'),
    updatedAt: new Date('2027-06-08'),
    voucher: {
      id: 'v-137',
      voucherNumber: 137,
      receiptImageUrl: null,
      notes: 'Summer camp concession supplies',
      createdAt: new Date('2027-06-08'),
      updatedAt: new Date('2027-06-08'),
    },
  },
  {
    id: 'demo-138',
    date: new Date('2027-06-20'),
    category: 'Interest Checking (W)',
    voucherNumber: 138,
    vendor: 'First National Bank',
    amount: 5.0,
    type: 'WITHDRAWAL',
    cleared: true,
    notes: null,
    receipts: [],
    createdAt: new Date('2027-06-20'),
    updatedAt: new Date('2027-06-20'),
    voucher: {
      id: 'v-138',
      voucherNumber: 138,
      receiptImageUrl: null,
      notes: 'Monthly account service fee',
      createdAt: new Date('2027-06-20'),
      updatedAt: new Date('2027-06-20'),
    },
  },
  {
    id: 'demo-139',
    date: new Date('2027-06-25'),
    category: 'Other (W)',
    voucherNumber: 139,
    vendor: 'Staples',
    amount: 195.99,
    type: 'WITHDRAWAL',
    cleared: true,
    notes: null,
    receipts: [],
    createdAt: new Date('2027-06-25'),
    updatedAt: new Date('2027-06-25'),
    voucher: {
      id: 'v-139',
      voucherNumber: 139,
      receiptImageUrl: null,
      notes: 'Summer program supplies',
      createdAt: new Date('2027-06-25'),
      updatedAt: new Date('2027-06-25'),
    },
  },
  {
    id: 'demo-140',
    date: new Date('2027-06-28'),
    category: 'Director of Band (W)',
    voucherNumber: 140,
    vendor: 'Yamaha Music',
    amount: 3400.0,
    type: 'WITHDRAWAL',
    cleared: false,
    notes: null,
    receipts: [],
    createdAt: new Date('2027-06-28'),
    updatedAt: new Date('2027-06-28'),
    voucher: {
      id: 'v-140',
      voucherNumber: 140,
      receiptImageUrl: null,
      notes: 'New percussion equipment for fall',
      createdAt: new Date('2027-06-28'),
      updatedAt: new Date('2027-06-28'),
    },
  },
]

// Extract vouchers from transactions for the vouchers page
export const demoVouchers = demoTransactions.map((t) => t.voucher).filter((v, index, self) => 
  index === self.findIndex((v2) => v2.voucherNumber === v.voucherNumber)
)