export const demoTransactions = [
  {
    id: 'demo-1',
    date: new Date('2024-09-01'),
    category: 'Donations (D)',
    voucherNumber: 1,
    vendor: 'John & Mary Smith',
    amount: 250.0,
    type: 'DEPOSIT',
    cleared: true,
    createdAt: new Date('2024-09-01'),
    updatedAt: new Date('2024-09-01'),
    voucher: {
      id: 'v-1',
      voucherNumber: 1,
      receiptImageUrl: null,
      notes: 'Annual family donation',
      createdAt: new Date('2024-09-01'),
      updatedAt: new Date('2024-09-01'),
    },
  },
  {
    id: 'demo-2',
    date: new Date('2024-09-03'),
    category: 'Concessions (D)',
    voucherNumber: 2,
    vendor: 'Friday Night Football Sales',
    amount: 875.5,
    type: 'DEPOSIT',
    cleared: true,
    createdAt: new Date('2024-09-03'),
    updatedAt: new Date('2024-09-03'),
    voucher: {
      id: 'v-2',
      voucherNumber: 2,
      receiptImageUrl: 'https://placehold.co/400x600/e2e8f0/1e293b?text=Receipt+%232\nConcessions',
      notes: 'Hot dogs, drinks, popcorn — sold out by halftime!',
      createdAt: new Date('2024-09-03'),
      updatedAt: new Date('2024-09-03'),
    },
  },
  {
    id: 'demo-3',
    date: new Date('2024-09-05'),
    category: 'Fundraiser (D)',
    voucherNumber: 3,
    vendor: 'Cookie Dough Sales',
    amount: 1200.0,
    type: 'DEPOSIT',
    cleared: true,
    createdAt: new Date('2024-09-05'),
    updatedAt: new Date('2024-09-05'),
    voucher: {
      id: 'v-3',
      voucherNumber: 3,
      receiptImageUrl: null,
      notes: 'Fall fundraiser proceeds — 48 students participated',
      createdAt: new Date('2024-09-05'),
      updatedAt: new Date('2024-09-05'),
    },
  },
  {
    id: 'demo-4',
    date: new Date('2024-09-08'),
    category: 'Director of Band (W)',
    voucherNumber: 4,
    vendor: 'Samuel Ash Music',
    amount: 450.0,
    type: 'WITHDRAWAL',
    cleared: true,
    createdAt: new Date('2024-09-08'),
    updatedAt: new Date('2024-09-08'),
    voucher: {
      id: 'v-4',
      voucherNumber: 4,
      receiptImageUrl: 'https://placehold.co/400x600/fee2e2/7f1d1d?text=Receipt+%234\nSheet+Music',
      notes: 'Marching band show music order — invoice #SA-8842',
      createdAt: new Date('2024-09-08'),
      updatedAt: new Date('2024-09-08'),
    },
  },
  {
    id: 'demo-5',
    date: new Date('2024-09-10'),
    category: 'Concessions (W)',
    voucherNumber: 5,
    vendor: 'Sysco Food Services',
    amount: 325.75,
    type: 'WITHDRAWAL',
    cleared: true,
    createdAt: new Date('2024-09-10'),
    updatedAt: new Date('2024-09-10'),
    voucher: {
      id: 'v-5',
      voucherNumber: 5,
      receiptImageUrl: null,
      notes: 'Food supplies for concessions — hot dog buns, nacho cheese, napkins',
      createdAt: new Date('2024-09-10'),
      updatedAt: new Date('2024-09-10'),
    },
  },
  {
    id: 'demo-6',
    date: new Date('2024-09-12'),
    category: 'Interest Checking (D)',
    voucherNumber: 6,
    vendor: 'First National Bank',
    amount: 12.34,
    type: 'DEPOSIT',
    cleared: true,
    createdAt: new Date('2024-09-12'),
    updatedAt: new Date('2024-09-12'),
    voucher: {
      id: 'v-6',
      voucherNumber: 6,
      receiptImageUrl: null,
      notes: null,
      createdAt: new Date('2024-09-12'),
      updatedAt: new Date('2024-09-12'),
    },
  },
  {
    id: 'demo-7',
    date: new Date('2024-09-15'),
    category: 'Credit Card Machine (D)',
    voucherNumber: 7,
    vendor: 'Square Processing',
    amount: 234.0,
    type: 'DEPOSIT',
    cleared: false,
    createdAt: new Date('2024-09-15'),
    updatedAt: new Date('2024-09-15'),
    voucher: {
      id: 'v-7',
      voucherNumber: 7,
      receiptImageUrl: 'https://placehold.co/400x600/dcfce7/14532d?text=Receipt+%237\nSquare+Batch',
      notes: 'Credit card batch deposit — Sept 14 game day sales',
      createdAt: new Date('2024-09-15'),
      updatedAt: new Date('2024-09-15'),
    },
  },
  {
    id: 'demo-8',
    date: new Date('2024-09-18'),
    category: 'Other (D)',
    voucherNumber: 8,
    vendor: 'Car Wash Fundraiser',
    amount: 500.0,
    type: 'DEPOSIT',
    cleared: false,
    createdAt: new Date('2024-09-18'),
    updatedAt: new Date('2024-09-18'),
    voucher: {
      id: 'v-8',
      voucherNumber: 8,
      receiptImageUrl: null,
      notes: 'Community car wash event at Johnsons Auto Detail — 6 hours, 22 volunteers',
      createdAt: new Date('2024-09-18'),
      updatedAt: new Date('2024-09-18'),
    },
  },
  {
    id: 'demo-9',
    date: new Date('2024-09-20'),
    category: 'Other (W)',
    voucherNumber: 9,
    vendor: 'Office Depot',
    amount: 87.43,
    type: 'WITHDRAWAL',
    cleared: true,
    createdAt: new Date('2024-09-20'),
    updatedAt: new Date('2024-09-20'),
    voucher: {
      id: 'v-9',
      voucherNumber: 9,
      receiptImageUrl: 'https://placehold.co/400x600/fee2e2/7f1d1d?text=Receipt+%239\nOffice+Depot',
      notes: 'Printer ink, copy paper, manila envelopes',
      createdAt: new Date('2024-09-20'),
      updatedAt: new Date('2024-09-20'),
    },
  },
  {
    id: 'demo-10',
    date: new Date('2024-09-22'),
    category: 'Concessions (D)',
    voucherNumber: 10,
    vendor: 'Homecoming Game Sales',
    amount: 1340.0,
    type: 'DEPOSIT',
    cleared: false,
    createdAt: new Date('2024-09-22'),
    updatedAt: new Date('2024-09-22'),
    voucher: {
      id: 'v-10',
      voucherNumber: 10,
      receiptImageUrl: 'https://placehold.co/400x600/dcfce7/14532d?text=Receipt+%2310\nHomecoming',
      notes: 'Big game — record sales! Ran out of pretzels in 3rd quarter',
      createdAt: new Date('2024-09-22'),
      updatedAt: new Date('2024-09-22'),
    },
  },
  {
    id: 'demo-11',
    date: new Date('2024-09-25'),
    category: 'Concessions (W)',
    voucherNumber: 11,
    vendor: 'Coca-Cola Distributing',
    amount: 215.0,
    type: 'WITHDRAWAL',
    cleared: true,
    createdAt: new Date('2024-09-25'),
    updatedAt: new Date('2024-09-25'),
    voucher: {
      id: 'v-11',
      voucherNumber: 11,
      receiptImageUrl: null,
      notes: 'Beverage restock — 10 cases Coke, 8 cases Sprite, 5 cases water',
      createdAt: new Date('2024-09-25'),
      updatedAt: new Date('2024-09-25'),
    },
  },
  {
    id: 'demo-12',
    date: new Date('2024-09-28'),
    category: 'Donations (D)',
    voucherNumber: 12,
    vendor: 'Local Business Sponsorship',
    amount: 500.0,
    type: 'DEPOSIT',
    cleared: true,
    createdAt: new Date('2024-09-28'),
    updatedAt: new Date('2024-09-28'),
    voucher: {
      id: 'v-12',
      voucherNumber: 12,
      receiptImageUrl: 'https://placehold.co/400x600/dcfce7/14532d?text=Receipt+%2312\nSponsorship',
      notes: 'Smith Auto Repair — banner sponsorship for fall season',
      createdAt: new Date('2024-09-28'),
      updatedAt: new Date('2024-09-28'),
    },
  },
  {
    id: 'demo-13',
    date: new Date('2024-10-02'),
    category: 'Fundraiser (D)',
    voucherNumber: 13,
    vendor: 'Bingo Night Tickets',
    amount: 680.0,
    type: 'DEPOSIT',
    cleared: true,
    createdAt: new Date('2024-10-02'),
    updatedAt: new Date('2024-10-02'),
    voucher: {
      id: 'v-13',
      voucherNumber: 13,
      receiptImageUrl: null,
      notes: 'Community bingo night — 85 tickets sold, prizes donated by local businesses',
      createdAt: new Date('2024-10-02'),
      updatedAt: new Date('2024-10-02'),
    },
  },
  {
    id: 'demo-14',
    date: new Date('2024-10-05'),
    category: 'Director of Band (W)',
    voucherNumber: 14,
    vendor: 'Midwest Music Supply',
    amount: 1240.0,
    type: 'WITHDRAWAL',
    cleared: false,
    createdAt: new Date('2024-10-05'),
    updatedAt: new Date('2024-10-05'),
    voucher: {
      id: 'v-14',
      voucherNumber: 14,
      receiptImageUrl: 'https://placehold.co/400x600/fee2e2/7f1d1d?text=Receipt+%2314\nInstruments',
      notes: 'Replacement marching baritone — invoice #MWS-9912, net 30 terms',
      createdAt: new Date('2024-10-05'),
      updatedAt: new Date('2024-10-05'),
    },
  },
  {
    id: 'demo-15',
    date: new Date('2024-10-08'),
    category: 'Interest Checking (W)',
    voucherNumber: 15,
    vendor: 'First National Bank',
    amount: 5.0,
    type: 'WITHDRAWAL',
    cleared: true,
    createdAt: new Date('2024-10-08'),
    updatedAt: new Date('2024-10-08'),
    voucher: {
      id: 'v-15',
      voucherNumber: 15,
      receiptImageUrl: null,
      notes: 'Monthly account service fee',
      createdAt: new Date('2024-10-08'),
      updatedAt: new Date('2024-10-08'),
    },
  },
  {
    id: 'demo-16',
    date: new Date('2024-10-12'),
    category: 'Concessions (D)',
    voucherNumber: 16,
    vendor: 'Rival Game Night Sales',
    amount: 945.0,
    type: 'DEPOSIT',
    cleared: false,
    createdAt: new Date('2024-10-12'),
    updatedAt: new Date('2024-10-12'),
    voucher: {
      id: 'v-16',
      voucherNumber: 16,
      receiptImageUrl: null,
      notes: 'Away game concessions — weather delay, still strong turnout',
      createdAt: new Date('2024-10-12'),
      updatedAt: new Date('2024-10-12'),
    },
  },
]

export const demoVouchers = demoTransactions.map((t) => t.voucher)

export function getDemoOverview() {
  const transactions = demoTransactions

  const totalDeposits = transactions
    .filter((t) => t.type === 'DEPOSIT')
    .reduce((sum, t) => sum + t.amount, 0)

  const totalWithdrawals = transactions
    .filter((t) => t.type === 'WITHDRAWAL')
    .reduce((sum, t) => sum + t.amount, 0)

  const balance = totalDeposits - totalWithdrawals

  const clearedDeposits = transactions
    .filter((t) => t.type === 'DEPOSIT' && t.cleared)
    .reduce((sum, t) => sum + t.amount, 0)

  const clearedWithdrawals = transactions
    .filter((t) => t.type === 'WITHDRAWAL' && t.cleared)
    .reduce((sum, t) => sum + t.amount, 0)

  const clearedBalance = clearedDeposits - clearedWithdrawals

  const pendingDeposits = totalDeposits - clearedDeposits
  const pendingWithdrawals = totalWithdrawals - clearedWithdrawals

  return {
    balance,
    clearedBalance,
    pendingBalance: balance - clearedBalance,
    totalDeposits,
    totalWithdrawals,
    clearedDeposits,
    clearedWithdrawals,
    pendingDeposits,
    pendingWithdrawals,
    transactionCount: transactions.length,
  }
}

