export const demoTransactions = [
  // 2025 Transactions
  {
    id: 'demo-1',
    date: new Date('2025-01-15'),
    category: 'Donations (D)',
    voucherNumber: 1,
    vendor: 'Johnson Family',
    amount: 500.0,
    type: 'DEPOSIT',
    cleared: true,
    createdAt: new Date('2025-01-15'),
    updatedAt: new Date('2025-01-15'),
    voucher: {
      id: 'v-1',
      voucherNumber: 1,
      receiptImageUrl: null,
      notes: 'Annual donation for band program',
      createdAt: new Date('2025-01-15'),
      updatedAt: new Date('2025-01-15'),
    },
  },
  {
    id: 'demo-2',
    date: new Date('2025-01-22'),
    category: 'Concessions (D)',
    voucherNumber: 2,
    vendor: 'Basketball Game Sales',
    amount: 340.5,
    type: 'DEPOSIT',
    cleared: true,
    createdAt: new Date('2025-01-22'),
    updatedAt: new Date('2025-01-22'),
    voucher: {
      id: 'v-2',
      voucherNumber: 2,
      receiptImageUrl: null,
      notes: 'Winter basketball concessions',
      createdAt: new Date('2025-01-22'),
      updatedAt: new Date('2025-01-22'),
    },
  },
  {
    id: 'demo-3',
    date: new Date('2025-02-10'),
    category: 'Fundraiser (D)',
    voucherNumber: 3,
    vendor: 'Valentine Candy Sales',
    amount: 890.0,
    type: 'DEPOSIT',
    cleared: true,
    createdAt: new Date('2025-02-10'),
    updatedAt: new Date('2025-02-10'),
    voucher: {
      id: 'v-3',
      voucherNumber: 3,
      receiptImageUrl: null,
      notes: 'Valentine fundraiser — 62 students sold candy grams',
      createdAt: new Date('2025-02-10'),
      updatedAt: new Date('2025-02-10'),
    },
  },
  {
    id: 'demo-4',
    date: new Date('2025-02-28'),
    category: 'Director of Band (W)',
    voucherNumber: 4,
    vendor: 'Hal Leonard Music',
    amount: 675.0,
    type: 'WITHDRAWAL',
    cleared: true,
    createdAt: new Date('2025-02-28'),
    updatedAt: new Date('2025-02-28'),
    voucher: {
      id: 'v-4',
      voucherNumber: 4,
      receiptImageUrl: null,
      notes: 'Spring concert sheet music order',
      createdAt: new Date('2025-02-28'),
      updatedAt: new Date('2025-02-28'),
    },
  },
  {
    id: 'demo-5',
    date: new Date('2025-03-15'),
    category: 'Concessions (D)',
    voucherNumber: 5,
    vendor: 'Spring Festival Sales',
    amount: 1250.0,
    type: 'DEPOSIT',
    cleared: true,
    createdAt: new Date('2025-03-15'),
    updatedAt: new Date('2025-03-15'),
    voucher: {
      id: 'v-5',
      voucherNumber: 5,
      receiptImageUrl: null,
      notes: 'Record sales at spring festival!',
      createdAt: new Date('2025-03-15'),
      updatedAt: new Date('2025-03-15'),
    },
  },
  {
    id: 'demo-6',
    date: new Date('2025-03-20'),
    category: 'Other (W)',
    voucherNumber: 6,
    vendor: 'Staples',
    amount: 145.33,
    type: 'WITHDRAWAL',
    cleared: true,
    createdAt: new Date('2025-03-20'),
    updatedAt: new Date('2025-03-20'),
    voucher: {
      id: 'v-6',
      voucherNumber: 6,
      receiptImageUrl: null,
      notes: 'Office supplies for band office',
      createdAt: new Date('2025-03-20'),
      updatedAt: new Date('2025-03-20'),
    },
  },
  {
    id: 'demo-7',
    date: new Date('2025-04-05'),
    category: 'Donations (D)',
    voucherNumber: 7,
    vendor: 'Smith Auto Repair',
    amount: 750.0,
    type: 'DEPOSIT',
    cleared: true,
    createdAt: new Date('2025-04-05'),
    updatedAt: new Date('2025-04-05'),
    voucher: {
      id: 'v-7',
      voucherNumber: 7,
      receiptImageUrl: null,
      notes: 'Spring sponsorship check',
      createdAt: new Date('2025-04-05'),
      updatedAt: new Date('2025-04-05'),
    },
  },
  {
    id: 'demo-8',
    date: new Date('2025-04-18'),
    category: 'Concessions (W)',
    voucherNumber: 8,
    vendor: 'Sam\'s Club',
    amount: 425.0,
    type: 'WITHDRAWAL',
    cleared: true,
    createdAt: new Date('2025-04-18'),
    updatedAt: new Date('2025-04-18'),
    voucher: {
      id: 'v-8',
      voucherNumber: 8,
      receiptImageUrl: null,
      notes: 'Bulk snacks and drinks for concessions',
      createdAt: new Date('2025-04-18'),
      updatedAt: new Date('2025-04-18'),
    },
  },
  {
    id: 'demo-9',
    date: new Date('2025-05-10'),
    category: 'Fundraiser (D)',
    voucherNumber: 9,
    vendor: 'Spring Car Wash',
    amount: 620.0,
    type: 'DEPOSIT',
    cleared: false,
    createdAt: new Date('2025-05-10'),
    updatedAt: new Date('2025-05-10'),
    voucher: {
      id: 'v-9',
      voucherNumber: 9,
      receiptImageUrl: null,
      notes: 'Community car wash — rainy day but still great turnout',
      createdAt: new Date('2025-05-10'),
      updatedAt: new Date('2025-05-10'),
    },
  },
  {
    id: 'demo-10',
    date: new Date('2025-05-25'),
    category: 'Interest Checking (D)',
    voucherNumber: 10,
    vendor: 'First National Bank',
    amount: 18.42,
    type: 'DEPOSIT',
    cleared: true,
    createdAt: new Date('2025-05-25'),
    updatedAt: new Date('2025-05-25'),
    voucher: {
      id: 'v-10',
      voucherNumber: 10,
      receiptImageUrl: null,
      notes: 'Monthly interest credit',
      createdAt: new Date('2025-05-25'),
      updatedAt: new Date('2025-05-25'),
    },
  },
  // Fiscal Year boundary — June 2025 starts FY 2025-2026
  {
    id: 'demo-11',
    date: new Date('2025-06-05'),
    category: 'Concessions (D)',
    voucherNumber: 11,
    vendor: 'Summer Camp Sales',
    amount: 780.0,
    type: 'DEPOSIT',
    cleared: true,
    createdAt: new Date('2025-06-05'),
    updatedAt: new Date('2025-06-05'),
    voucher: {
      id: 'v-11',
      voucherNumber: 11,
      receiptImageUrl: null,
      notes: 'Band summer camp concessions',
      createdAt: new Date('2025-06-05'),
      updatedAt: new Date('2025-06-05'),
    },
  },
  {
    id: 'demo-12',
    date: new Date('2025-06-20'),
    category: 'Director of Band (W)',
    voucherNumber: 12,
    vendor: 'Yamaha Music',
    amount: 3200.0,
    type: 'WITHDRAWAL',
    cleared: false,
    createdAt: new Date('2025-06-20'),
    updatedAt: new Date('2025-06-20'),
    voucher: {
      id: 'v-12',
      voucherNumber: 12,
      receiptImageUrl: null,
      notes: 'New percussion equipment for fall season',
      createdAt: new Date('2025-06-20'),
      updatedAt: new Date('2025-06-20'),
    },
  },
  {
    id: 'demo-13',
    date: new Date('2025-07-12'),
    category: 'Donations (D)',
    voucherNumber: 13,
    vendor: 'Alumni Association',
    amount: 1500.0,
    type: 'DEPOSIT',
    cleared: true,
    createdAt: new Date('2025-07-12'),
    updatedAt: new Date('2025-07-12'),
    voucher: {
      id: 'v-13',
      voucherNumber: 13,
      receiptImageUrl: null,
      notes: 'Annual alumni donation for marching band',
      createdAt: new Date('2025-07-12'),
      updatedAt: new Date('2025-07-12'),
    },
  },
  {
    id: 'demo-14',
    date: new Date('2025-08-08'),
    category: 'Other (D)',
    voucherNumber: 14,
    vendor: 'Garage Sale Fundraiser',
    amount: 340.0,
    type: 'DEPOSIT',
    cleared: true,
    createdAt: new Date('2025-08-08'),
    updatedAt: new Date('2025-08-08'),
    voucher: {
      id: 'v-14',
      voucherNumber: 14,
      receiptImageUrl: null,
      notes: 'Band families donated items for garage sale',
      createdAt: new Date('2025-08-08'),
      updatedAt: new Date('2025-08-08'),
    },
  },
  {
    id: 'demo-15',
    date: new Date('2025-09-01'),
    category: 'Concessions (D)',
    voucherNumber: 15,
    vendor: 'Friday Night Football Sales',
    amount: 875.5,
    type: 'DEPOSIT',
    cleared: true,
    createdAt: new Date('2025-09-01'),
    updatedAt: new Date('2025-09-01'),
    voucher: {
      id: 'v-15',
      voucherNumber: 15,
      receiptImageUrl: null,
      notes: 'Hot dogs, drinks, popcorn — sold out by halftime!',
      createdAt: new Date('2025-09-01'),
      updatedAt: new Date('2025-09-01'),
    },
  },
  {
    id: 'demo-16',
    date: new Date('2025-09-15'),
    category: 'Credit Card Machine (D)',
    voucherNumber: 16,
    vendor: 'Square Processing',
    amount: 445.0,
    type: 'DEPOSIT',
    cleared: false,
    createdAt: new Date('2025-09-15'),
    updatedAt: new Date('2025-09-15'),
    voucher: {
      id: 'v-16',
      voucherNumber: 16,
      receiptImageUrl: null,
      notes: 'Credit card batch — Sept 14 game day sales',
      createdAt: new Date('2025-09-15'),
      updatedAt: new Date('2025-09-15'),
    },
  },
  {
    id: 'demo-17',
    date: new Date('2025-10-05'),
    category: 'Fundraiser (D)',
    voucherNumber: 17,
    vendor: 'Cookie Dough Sales',
    amount: 1350.0,
    type: 'DEPOSIT',
    cleared: true,
    createdAt: new Date('2025-10-05'),
    updatedAt: new Date('2025-10-05'),
    voucher: {
      id: 'v-17',
      voucherNumber: 17,
      receiptImageUrl: null,
      notes: 'Fall fundraiser proceeds — 55 students participated',
      createdAt: new Date('2025-10-05'),
      updatedAt: new Date('2025-10-05'),
    },
  },
  {
    id: 'demo-18',
    date: new Date('2025-10-20'),
    category: 'Concessions (W)',
    voucherNumber: 18,
    vendor: 'Sysco Food Services',
    amount: 525.75,
    type: 'WITHDRAWAL',
    cleared: true,
    createdAt: new Date('2025-10-20'),
    updatedAt: new Date('2025-10-20'),
    voucher: {
      id: 'v-18',
      voucherNumber: 18,
      receiptImageUrl: null,
      notes: 'Food supplies for concessions restock',
      createdAt: new Date('2025-10-20'),
      updatedAt: new Date('2025-10-20'),
    },
  },
  {
    id: 'demo-19',
    date: new Date('2025-11-15'),
    category: 'Donations (D)',
    voucherNumber: 19,
    vendor: 'Local Business Sponsorship',
    amount: 1000.0,
    type: 'DEPOSIT',
    cleared: true,
    createdAt: new Date('2025-11-15'),
    updatedAt: new Date('2025-11-15'),
    voucher: {
      id: 'v-19',
      voucherNumber: 19,
      receiptImageUrl: null,
      notes: 'Winter sponsorship — banner ad at all home games',
      createdAt: new Date('2025-11-15'),
      updatedAt: new Date('2025-11-15'),
    },
  },
  {
    id: 'demo-20',
    date: new Date('2025-12-10'),
    category: 'Concessions (D)',
    voucherNumber: 20,
    vendor: 'Holiday Tournament Sales',
    amount: 1100.0,
    type: 'DEPOSIT',
    cleared: true,
    createdAt: new Date('2025-12-10'),
    updatedAt: new Date('2025-12-10'),
    voucher: {
      id: 'v-20',
      voucherNumber: 20,
      receiptImageUrl: null,
      notes: 'Holiday basketball tournament — great turnout',
      createdAt: new Date('2025-12-10'),
      updatedAt: new Date('2025-12-10'),
    },
  },
  // 2026 Transactions
  {
    id: 'demo-21',
    date: new Date('2026-01-20'),
    category: 'Interest Checking (W)',
    voucherNumber: 21,
    vendor: 'First National Bank',
    amount: 5.0,
    type: 'WITHDRAWAL',
    cleared: true,
    createdAt: new Date('2026-01-20'),
    updatedAt: new Date('2026-01-20'),
    voucher: {
      id: 'v-21',
      voucherNumber: 21,
      receiptImageUrl: null,
      notes: 'Monthly account service fee',
      createdAt: new Date('2026-01-20'),
      updatedAt: new Date('2026-01-20'),
    },
  },
  {
    id: 'demo-22',
    date: new Date('2026-02-14'),
    category: 'Fundraiser (D)',
    voucherNumber: 22,
    vendor: 'Valentine Rose Sales',
    amount: 720.0,
    type: 'DEPOSIT',
    cleared: true,
    createdAt: new Date('2026-02-14'),
    updatedAt: new Date('2026-02-14'),
    voucher: {
      id: 'v-22',
      voucherNumber: 22,
      receiptImageUrl: null,
      notes: 'Valentine roses fundraiser',
      createdAt: new Date('2026-02-14'),
      updatedAt: new Date('2026-02-14'),
    },
  },
  {
    id: 'demo-23',
    date: new Date('2026-03-08'),
    category: 'Concessions (D)',
    voucherNumber: 23,
    vendor: 'State Championship Sales',
    amount: 2100.0,
    type: 'DEPOSIT',
    cleared: true,
    createdAt: new Date('2026-03-08'),
    updatedAt: new Date('2026-03-08'),
    voucher: {
      id: 'v-23',
      voucherNumber: 23,
      receiptImageUrl: null,
      notes: 'State championship game — record concession sales!',
      createdAt: new Date('2026-03-08'),
      updatedAt: new Date('2026-03-08'),
    },
  },
  {
    id: 'demo-24',
    date: new Date('2026-03-22'),
    category: 'Director of Band (W)',
    voucherNumber: 24,
    vendor: 'Midwest Music Supply',
    amount: 1850.0,
    type: 'WITHDRAWAL',
    cleared: false,
    createdAt: new Date('2026-03-22'),
    updatedAt: new Date('2026-03-22'),
    voucher: {
      id: 'v-24',
      voucherNumber: 24,
      receiptImageUrl: null,
      notes: 'New brass instruments for spring season',
      createdAt: new Date('2026-03-22'),
      updatedAt: new Date('2026-03-22'),
    },
  },
  {
    id: 'demo-25',
    date: new Date('2026-04-10'),
    category: 'Donations (D)',
    voucherNumber: 25,
    vendor: 'Community Foundation',
    amount: 2500.0,
    type: 'DEPOSIT',
    cleared: true,
    createdAt: new Date('2026-04-10'),
    updatedAt: new Date('2026-04-10'),
    voucher: {
      id: 'v-25',
      voucherNumber: 25,
      receiptImageUrl: null,
      notes: 'Spring grant for music education',
      createdAt: new Date('2026-04-10'),
      updatedAt: new Date('2026-04-10'),
    },
  },
  {
    id: 'demo-26',
    date: new Date('2026-05-05'),
    category: 'Concessions (W)',
    voucherNumber: 26,
    vendor: 'Coca-Cola Distributing',
    amount: 315.0,
    type: 'WITHDRAWAL',
    cleared: true,
    createdAt: new Date('2026-05-05'),
    updatedAt: new Date('2026-05-05'),
    voucher: {
      id: 'v-26',
      voucherNumber: 26,
      receiptImageUrl: null,
      notes: 'Beverage restock for end of year events',
      createdAt: new Date('2026-05-05'),
      updatedAt: new Date('2026-05-05'),
    },
  },
  // Fiscal Year boundary — June 2026 starts FY 2026-2027
  {
    id: 'demo-27',
    date: new Date('2026-06-15'),
    category: 'Other (D)',
    voucherNumber: 27,
    vendor: 'Summer Camp Registration',
    amount: 450.0,
    type: 'DEPOSIT',
    cleared: true,
    createdAt: new Date('2026-06-15'),
    updatedAt: new Date('2026-06-15'),
    voucher: {
      id: 'v-27',
      voucherNumber: 27,
      receiptImageUrl: null,
      notes: 'Band summer camp fees',
      createdAt: new Date('2026-06-15'),
      updatedAt: new Date('2026-06-15'),
    },
  },
  {
    id: 'demo-28',
    date: new Date('2026-07-04'),
    category: 'Concessions (D)',
    voucherNumber: 28,
    vendor: 'July 4th Festival',
    amount: 950.0,
    type: 'DEPOSIT',
    cleared: true,
    createdAt: new Date('2026-07-04'),
    updatedAt: new Date('2026-07-04'),
    voucher: {
      id: 'v-28',
      voucherNumber: 28,
      receiptImageUrl: null,
      notes: 'Fourth of July parade and festival concessions',
      createdAt: new Date('2026-07-04'),
      updatedAt: new Date('2026-07-04'),
    },
  },
  {
    id: 'demo-29',
    date: new Date('2026-08-20'),
    category: 'Fundraiser (D)',
    voucherNumber: 29,
    vendor: 'Back-to-School BBQ',
    amount: 680.0,
    type: 'DEPOSIT',
    cleared: true,
    createdAt: new Date('2026-08-20'),
    updatedAt: new Date('2026-08-20'),
    voucher: {
      id: 'v-29',
      voucherNumber: 29,
      receiptImageUrl: null,
      notes: 'Annual back-to-school BBQ fundraiser',
      createdAt: new Date('2026-08-20'),
      updatedAt: new Date('2026-08-20'),
    },
  },
  {
    id: 'demo-30',
    date: new Date('2026-09-10'),
    category: 'Donations (D)',
    voucherNumber: 30,
    vendor: 'Miller Family Trust',
    amount: 1200.0,
    type: 'DEPOSIT',
    cleared: true,
    createdAt: new Date('2026-09-10'),
    updatedAt: new Date('2026-09-10'),
    voucher: {
      id: 'v-30',
      voucherNumber: 30,
      receiptImageUrl: null,
      notes: 'Annual trust donation for band scholarships',
      createdAt: new Date('2026-09-10'),
      updatedAt: new Date('2026-09-10'),
    },
  },
  {
    id: 'demo-31',
    date: new Date('2026-10-02'),
    category: 'Concessions (D)',
    voucherNumber: 31,
    vendor: 'Homecoming Game Sales',
    amount: 1650.0,
    type: 'DEPOSIT',
    cleared: true,
    createdAt: new Date('2026-10-02'),
    updatedAt: new Date('2026-10-02'),
    voucher: {
      id: 'v-31',
      voucherNumber: 31,
      receiptImageUrl: null,
      notes: 'Homecoming game — sold out of everything!',
      createdAt: new Date('2026-10-02'),
      updatedAt: new Date('2026-10-02'),
    },
  },
  {
    id: 'demo-32',
    date: new Date('2026-10-18'),
    category: 'Director of Band (W)',
    voucherNumber: 32,
    vendor: 'Samuel Ash Music',
    amount: 2100.0,
    type: 'WITHDRAWAL',
    cleared: false,
    createdAt: new Date('2026-10-18'),
    updatedAt: new Date('2026-10-18'),
    voucher: {
      id: 'v-32',
      voucherNumber: 32,
      receiptImageUrl: null,
      notes: 'Marching band show music and drill design',
      createdAt: new Date('2026-10-18'),
      updatedAt: new Date('2026-10-18'),
    },
  },
  {
    id: 'demo-33',
    date: new Date('2026-11-22'),
    category: 'Credit Card Machine (D)',
    voucherNumber: 33,
    vendor: 'Square Processing',
    amount: 580.0,
    type: 'DEPOSIT',
    cleared: true,
    createdAt: new Date('2026-11-22'),
    updatedAt: new Date('2026-11-22'),
    voucher: {
      id: 'v-33',
      voucherNumber: 33,
      receiptImageUrl: null,
      notes: 'Credit card sales — Thanksgiving tournament',
      createdAt: new Date('2026-11-22'),
      updatedAt: new Date('2026-11-22'),
    },
  },
  {
    id: 'demo-34',
    date: new Date('2026-12-15'),
    category: 'Concessions (W)',
    voucherNumber: 34,
    vendor: 'Costco Wholesale',
    amount: 780.0,
    type: 'WITHDRAWAL',
    cleared: true,
    createdAt: new Date('2026-12-15'),
    updatedAt: new Date('2026-12-15'),
    voucher: {
      id: 'v-34',
      voucherNumber: 34,
      receiptImageUrl: null,
      notes: 'Holiday tournament concessions stock-up',
      createdAt: new Date('2026-12-15'),
      updatedAt: new Date('2026-12-15'),
    },
  },
  // 2027 Transactions
  {
    id: 'demo-35',
    date: new Date('2027-01-10'),
    category: 'Donations (D)',
    voucherNumber: 35,
    vendor: 'Winter Gala Sponsors',
    amount: 3000.0,
    type: 'DEPOSIT',
    cleared: true,
    createdAt: new Date('2027-01-10'),
    updatedAt: new Date('2027-01-10'),
    voucher: {
      id: 'v-35',
      voucherNumber: 35,
      receiptImageUrl: null,
      notes: 'Winter gala corporate sponsors',
      createdAt: new Date('2027-01-10'),
      updatedAt: new Date('2027-01-10'),
    },
  },
  {
    id: 'demo-36',
    date: new Date('2027-02-20'),
    category: 'Fundraiser (D)',
    voucherNumber: 36,
    vendor: 'Chocolate Bar Sales',
    amount: 950.0,
    type: 'DEPOSIT',
    cleared: true,
    createdAt: new Date('2027-02-20'),
    updatedAt: new Date('2027-02-20'),
    voucher: {
      id: 'v-36',
      voucherNumber: 36,
      receiptImageUrl: null,
      notes: 'World\'s Finest Chocolate fundraiser',
      createdAt: new Date('2027-02-20'),
      updatedAt: new Date('2027-02-20'),
    },
  },
  {
    id: 'demo-37',
    date: new Date('2027-03-15'),
    category: 'Concessions (D)',
    voucherNumber: 37,
    vendor: 'March Madness Sales',
    amount: 1450.0,
    type: 'DEPOSIT',
    cleared: true,
    createdAt: new Date('2027-03-15'),
    updatedAt: new Date('2027-03-15'),
    voucher: {
      id: 'v-37',
      voucherNumber: 37,
      receiptImageUrl: null,
      notes: 'March basketball tournament concessions',
      createdAt: new Date('2027-03-15'),
      updatedAt: new Date('2027-03-15'),
    },
  },
  {
    id: 'demo-38',
    date: new Date('2027-03-28'),
    category: 'Other (W)',
    voucherNumber: 38,
    vendor: 'Office Depot',
    amount: 210.5,
    type: 'WITHDRAWAL',
    cleared: true,
    createdAt: new Date('2027-03-28'),
    updatedAt: new Date('2027-03-28'),
    voucher: {
      id: 'v-38',
      voucherNumber: 38,
      receiptImageUrl: null,
      notes: 'Spring concert programs and posters',
      createdAt: new Date('2027-03-28'),
      updatedAt: new Date('2027-03-28'),
    },
  },
  {
    id: 'demo-39',
    date: new Date('2027-04-05'),
    category: 'Interest Checking (D)',
    voucherNumber: 39,
    vendor: 'First National Bank',
    amount: 32.18,
    type: 'DEPOSIT',
    cleared: true,
    createdAt: new Date('2027-04-05'),
    updatedAt: new Date('2027-04-05'),
    voucher: {
      id: 'v-39',
      voucherNumber: 39,
      receiptImageUrl: null,
      notes: 'Quarterly interest credit',
      createdAt: new Date('2027-04-05'),
      updatedAt: new Date('2027-04-05'),
    },
  },
  {
    id: 'demo-40',
    date: new Date('2027-05-12'),
    category: 'Concessions (D)',
    voucherNumber: 40,
    vendor: 'Spring Fair Sales',
    amount: 880.0,
    type: 'DEPOSIT',
    cleared: false,
    createdAt: new Date('2027-05-12'),
    updatedAt: new Date('2027-05-12'),
    voucher: {
      id: 'v-40',
      voucherNumber: 40,
      receiptImageUrl: null,
      notes: 'Annual spring fair concessions',
      createdAt: new Date('2027-05-12'),
      updatedAt: new Date('2027-05-12'),
    },
  },
]

export const demoVouchers = demoTransactions.map((t) => t.voucher)

export function getDemoOverview() {
  const transactions = demoTransactions

  const totalDeposits = transactions
    .filter((t) => t.type === 'DEPOSIT')
    .reduce((sum, t) => sum + t.amount, 0)

  const totalWithdrawals = transactions
    .filter((t) => t.type === 'WITHDRAWAL')
    .reduce((sum, t) => sum + t.amount, 0)

  const balance = totalDeposits - totalWithdrawals

  const clearedDeposits = transactions
    .filter((t) => t.type === 'DEPOSIT' && t.cleared)
    .reduce((sum, t) => sum + t.amount, 0)

  const clearedWithdrawals = transactions
    .filter((t) => t.type === 'WITHDRAWAL' && t.cleared)
    .reduce((sum, t) => sum + t.amount, 0)

  const clearedBalance = clearedDeposits - clearedWithdrawals

  const pendingDeposits = totalDeposits - clearedDeposits
  const pendingWithdrawals = totalWithdrawals - clearedWithdrawals

  return {
    balance,
    clearedBalance,
    pendingBalance: balance - clearedBalance,
    totalDeposits,
    totalWithdrawals,
    clearedDeposits,
    clearedWithdrawals,
    pendingDeposits,
    pendingWithdrawals,
    transactionCount: transactions.length,
  }
}

